README.md
=> readme: add GA warning

README.md
=> readme: update backup pv support note

README.md, example/deployment-aws.yaml
Given investigation in #341 AWS ebs provisioner is supported.
=> readme: Update AWS PV provisioner support statement, fix delete command

pkg/controller/controller.go, pkg/util/k8sutil/backup.go
ref: #342
For this issue, ideally we should have some way to reject user spec that doesn't match our expectation. However, there is no admission control for TPR objects yet.
Nonetheless, such error shouldn't crash controller. As a fix for this, we will fail the cluster only, i.e. make the cluster die itself.
=> controller: fix crash on failure to create backup

pkg/controller/controller.go, pkg/util/k8sutil/backup.go
This PR is trying to differentiate the names of different storage classes.
etcd operator will create a storage class automatically. The problem is that storage class is shared across the cluster, not by namespace. So if I want to have and use different storage class, it's not possible before. Nonetheless, a cluster could have multiple etcd operator. They could use different storage class. Ideally, they don't overlapped with each other.
With this PR, I'm making the storage class name associated with storage class. The name has a format:
```
"etcd-operator-backup-" + path.Base(provisioner)
```
For example, if provisioner is "kubernetes.io/aws-ebs", the storage class name is "etcd-operator-backup-aws-ebs".
=> backup: differentiate storage class names

pkg/cluster/cluster.go, pkg/util/k8sutil/k8sutil.go
=> *: create client service for all etcd client endpoints

README.md, example/example-etcd-cluster-with-backup.yaml, example/example-etcd-cluster.yaml
=> doc/example: do not use backup in spec by default

pkg/cluster/cluster.go, pkg/cluster/reconcile.go, pkg/cluster/upgrade.go, test/e2e/e2e_test.go
=> cluster: use field logger

pkg/analytics/client.go
=> analytics: fix typo

pkg/cluster/cluster.go, pkg/controller/controller.go
=> controller: cleanup logging

pkg/cluster/cluster.go, pkg/cluster/reconcile.go, pkg/cluster/self_hosted.go, pkg/spec/cluster.go, pkg/util/etcdutil/member.go, pkg/util/k8sutil/k8sutil.go, pkg/util/k8sutil/pod_util.go, pkg/util/k8sutil/self_hosted.go, test/e2e/self_hosted_test.go
1. use host network
2. enable anti-affinity
=> Support self hosted cluster

pkg/cluster/self_hosted.go, pkg/util/k8sutil/k8sutil.go, test/e2e/framework/framework.go
=> *: CreateAndWaitPod returns the new pod status

test/e2e/util.go
One benefit of doing this is that we don't need to run proxy on test machine to route service IP.
=> e2e: refactor make backup using pod IP

ROADMAP.md
=> ROADMAP: update

pkg/cluster/cluster.go, pkg/cluster/reconcile.go, pkg/cluster/self_hosted.go, pkg/cluster/upgrade.go, pkg/controller/controller.go
Also refactor New() params into Config
=> cluster: refactor New() params into Config

README.md, doc/best_practices.md
/cc @hongchaodeng @colhom @joshix
=> doc: add best practices

doc/design/cluster_status.md
=> doc: add cluster status design

pkg/cluster/cluster.go, pkg/spec/cluster.go, pkg/util/k8sutil/backup.go, test/e2e/e2e_test.go, test/e2e/restore_test.go, test/e2e/util.go
This PR ignores the part on "BackupClusterName" now.
We will incrementally implement it later.
=> cluster: implement Restore policy

pkg/backup/backup.go, pkg/backup/file.go, pkg/backup/http.go, pkg/backup/version.go
prepare for adding s3 backup backend.
=> backup: move all file related ops to file.go

pkg/backup/backend.go, pkg/backup/backup.go, pkg/backup/backup_test.go, pkg/backup/file.go, pkg/backup/http.go
=> backup: abstract file backend as backend interface

pkg/backup/file.go, pkg/backup/s3.go, pkg/backup/util.go
=> backup: add s3 backend

pkg/backup/backup.go, pkg/spec/backup.go
=> backup: add s3 storage type support

cmd/backup/main.go
=> backup: minor rename

pkg/cluster/cluster.go
Close #433
All we need to ensure is that we only initialize PVC and other stuff for a completely new cluster.
=> cluster: do not intilize cluster on restore case

pkg/cluster/cluster.go, pkg/spec/cluster.go
=> cluster: refactor backup init

cmd/operator/main.go, pkg/cluster/cluster.go, pkg/controller/controller.go
ref: https://github.com/coreos/etcd-operator/pull/442
=> operator: AWS, S3 flags for cluster

README.md, example/example-etcd-cluster-nodeport-service.json, example/example-etcd-cluster.yaml
Mostly update “etcd-cluster” to “example-etcd-cluster”. Also did minor
updates per looking.
=> example: rename etcd-cluster to example-etcd-cluster

pkg/util/k8sutil/backup.go
config env should be set to exact config path
=> s3: fix config env

hack/jenkins
We have new config setup in Jenkins jobs.
This change is to make use of the new config.
=> jenkins: minor update to match new setup

hack/jenkins, test/e2e/aws_test.go, test/e2e/e2e_test.go, test/e2e/framework/framework.go, test/e2e/util.go
note:
- jenkins config change: S3_TEST_ENABLED -> AWS_TEST_ENABLED
=> e2e: add S3 test

pkg/cluster/cluster.go, pkg/spec/backup.go, test/e2e/util.go
The "CleanupOnClusterDelete" is ambiguous.
=> backup spec: CleanupOnClusterDelete -> CleanupBackupsOnClusterDelete

pkg/cluster/backupmanager/backup_manager.go, pkg/cluster/backupmanager/pv.go, pkg/cluster/backupmanager/s3.go, pkg/cluster/cluster.go
We need to handle S3 case as well.
Decided to add a method in backup manager and also make backupmanager a
field in cluster.
=> backup: fix CleanupBackups path

pkg/cluster/cluster.go
Previously, bm creation resides in isNewCluster block.
This won't tolerate controller restore case.
We should create it outside.
=> cluster: backupmanager tolerate controller restore

pkg/backup/backup.go, pkg/backup/s3/s3.go, pkg/cluster/backupmanager/s3.go, pkg/cluster/cluster.go, test/e2e/aws_test.go, test/e2e/restore_test.go, test/e2e/util.go
=> s3: implement restore from backup

pkg/backup/backend.go, pkg/backup/backup.go, pkg/backup/file.go, pkg/backup/s3.go, pkg/backup/util.go
=> backup: add purge for file backend

pkg/backup/util_test.go
=> backup: add sort unit test

pkg/backup/backend.go, pkg/backup/backup.go, pkg/backup/file.go, pkg/backup/s3.go
We might need to set up the minio-go stuff to do unit testing
=> s3_backend: impl. purge

pkg/backup/file_backend_test.go, pkg/backup/util_test.go
=> backup: add getLastest test for filebackend

pkg/cluster/cluster.go
=> cluster: do not panic operator if one cluster is dead

pkg/util/k8sutil/backup.go, test/e2e/e2e_test.go, test/e2e/util.go
@xiang90 
This should cover “cleanupStorage” for PV type.
=> e2e: check backup RS and PVC deleted at the end

example/example-etcd-cluster-with-backup.yaml
Update backup interval name in example
=> Update backup interval name in example

test/e2e/e2e_test.go
=> e2e: delete most recent etcd pods

pkg/cluster/backup_manager.go, pkg/cluster/cluster.go, pkg/cluster/reconcile.go, pkg/cluster/self_hosted.go, pkg/cluster/upgrade.go, pkg/controller/controller.go
This refactor is to do further work on owner reference.
=> cluster: refactor to pass in spec.EtcdCluster object

pkg/cluster/backup_manager.go, pkg/cluster/cluster.go, pkg/cluster/reconcile.go, pkg/cluster/self_hosted.go, pkg/cluster/upgrade.go, pkg/controller/controller.go
Reverts coreos/etcd-operator#514
No agreement on owner ref yet:
See discussion in: https://github.com/coreos/etcd-operator/pull/515#issuecomment-269092292
=> Revert "cluster: refactor to pass in spec.EtcdCluster object"

doc/design/resource_ownership_and_GC.md
=> doc: resource ownership and GC

pkg/controller/controller.go, pkg/controller/gc.go
=> cluster: add initial gc implementation

pkg/util/k8sutil/tpr_util.go, test/e2e/util.go
=> k8sutil: move TPR update to k8sutil

pkg/util/k8sutil/k8sutil.go
NodePort Svc is some useless legacy code
=> k8sutil: remove node port svc stuff 

pkg/spec/cluster.go
=> spec: rich status

pkg/cluster/backup_manager.go, pkg/cluster/cluster.go, pkg/cluster/self_hosted.go, pkg/spec/cluster.go, pkg/util/k8sutil/backup.go, pkg/util/k8sutil/k8sutil.go, pkg/util/k8sutil/self_hosted.go
Set etcd pod, svc, and backup RS, svc with owner ref to its single unique managing cluster.
=> cluster: add owner ref to cluster resources

pkg/cluster/cluster.go, pkg/util/k8sutil/tpr_util.go
=> cluster_status: update return specific NotFound err

pkg/cluster/cluster.go
ref: https://github.com/coreos/etcd-operator/issues/537#issuecomment-269404173
Add more logging for debugging issue
=> cluster: add logging in delete()

pkg/cluster/cluster.go
=> cluster: should check cluster.Status.Phase

pkg/util/k8sutil/tpr_util.go
GetCluster didn’t check http response code. Fix it.
=> k8sutil: fix http code checking and refactor

pkg/util/k8sutil/self_hosted.go
=> k8sutil: add checkpoint annotation for selfhosted etcd

pkg/cluster/self_hosted.go
=> self hosted: back off on member not ready

pkg/controller/controller.go, pkg/controller/gc.go, pkg/spec/etcd_cluster_list.go, pkg/util/k8sutil/tpr_util.go, test/e2e/framework/framework.go
This is to decouple GC from controller.
=> controller: refactor ListClusters and decouple GC

pkg/cluster/cluster.go, pkg/garbagecollection/gc.go
Deleting resources is quite dangerous. We better log it and have better knowledge of what was deleted
=> gc: log deleted resource

pkg/util/k8sutil/backup.go
PodCompleted doesn’t check PodFailed state. As a result, PodFailed
could also exit and lead to non-error return. We should only return on
PodSucceeded condition.
=> k8sutil: check PodSucceeded in CopyVolume

pkg/cluster/cluster.go
see https://github.com/coreos/etcd-operator/issues/594#issuecomment-270469603
=> cluster: more comprehensive status reason

pkg/util/k8sutil/backup.go, test/e2e/basic_test.go, test/e2e/recovery_test.go, test/e2e/resize_test.go, test/e2e/restore_test.go, test/e2e/self_hosted_test.go, test/e2e/util.go
combine checkBackupDeleted into deleteEtcdCluster at the end.
We will check all resources deleted in next step.
=> e2e: refactor deleteEtcdCluster

pkg/cluster/cluster.go
fix https://github.com/coreos/etcd-operator/issues/597
=> cluster: fix set status failed reason

test/e2e/util.go
Remove pod (etcd, operator)’s logs because they will be available on cloud.
Add more insights on what’s not deleted. Helps debug: https://github.com/coreos/etcd-operator/issues/607
=> e2e: remove pod log, add insight on delete

test/e2e/util.go
See https://github.com/coreos/etcd-operator/issues/606#issuecomment-270737397
We couldn’t get container status from cloud logging. This will help us understand why some pods/containers fail.
=> e2e: print container status at the end

pkg/util/k8sutil/backup.go
Helps debug https://github.com/coreos/etcd-operator/issues/588
=> copy_volume: add phase at err msg

pkg/util/k8sutil/backup.go
fix https://github.com/coreos/etcd-operator/issues/612
=> backup: ignore not found in delete

test/e2e/util.go
Can’t differentiate these two in https://github.com/coreos/etcd-operator/issues/612
=> e2e: separate checking to locate error

test/e2e/util.go
See if it helps to fix
https://github.com/coreos/etcd-operator/issues/607
=> e2e: increase retry times

pkg/backup/backup.go, test/e2e/recovery_test.go
fix https://github.com/coreos/etcd-operator/issues/602
=> backup: don't Fatal if fail to create etcd client

pkg/cluster/cluster.go
We are accessing EtcdCluster object while the cluster could be using it concurrently.
We should put it in run loop in sync-ed with other ops.
=> cluster: compare spec should be sync-ed with other ops

pkg/cluster/cluster.go
The previous code logic is unclear and error-prone since the if
condidtion describes the intended behavior not the state condition.
Changing the condition to state condition, and handling the condition
correctly.
=> cluster: fix failure handling code logic

test/e2e/basic_test.go, test/e2e/util.go
We have dismissed the logic in previous refactoring..
=> e2e: respect acceptPod

test/e2e/recovery_test.go, test/e2e/util.go
See https://github.com/coreos/etcd-operator/issues/627#issuecomment-271436663
=> e2e: killMembers ignore non-existent pod

pkg/cluster/cluster.go, pkg/cluster/member.go, pkg/cluster/self_hosted.go
=> cluster: improve selfhosted cluster reliability

hack/jenkins, hack/release/README.md
add “--strip-vendor --skip-test” to glide install
=> *: add glide install options

pkg/cluster/reconcile.go
=> make sure deadMembers will be removed before resize()

client/client.go, pkg/controller/controller.go, pkg/util/constants/constants.go
We need to update everything to use client-go or this client library wont work.
=> client: add initial implementation

pkg/util/etcdutil/etcdutil.go, test/e2e/restore_test.go
=> *: use the right context pkg for etcd API

README.md, doc/design/cluster_tls.md, doc/user/download_backup.md, pkg/util/k8sutil/k8sutil.go
also changed backup name from “xxx-backup-tool” to “xxx-backup-sidecar”.
This fixes #669. Partly solves #667
=> user_doc: download backup

test/e2e/self_hosted_test.go
=> test: remove bad removedir in self hosted test

pkg/backup/http.go, pkg/cluster/reconcile.go, pkg/util/http.go
=> backup: add v1 prefix to backup http endpoint

doc/user/download_backup.md
=> doc: fix download backup doc

doc/user/backup_service.md
=> doc: backup service doc

doc/user/download_backup.md, pkg/backup/s3/s3.go
Fix #673 
@hongchaodeng What is the plan for PV though? Can you fix that bit?
=> s3: add version prefix

README.md
fix https://github.com/coreos/etcd-operator/issues/699
=> readme: note about k8s 1.5 won't work

test/e2e/self_hosted_test.go
fix https://github.com/coreos/etcd-operator/issues/693
=> e2e: fix conflict of embed etcd dir

pkg/cluster/cluster.go, pkg/util/k8sutil/k8sutil.go
Continue https://github.com/coreos/etcd-operator/pull/680#discussion_r98117640
fix https://github.com/coreos/etcd-operator/issues/290
=> cluster: make each member's service owned by its pod

hack/build/operator/Dockerfile
fix https://github.com/coreos/etcd-operator/issues/709
=> dockerfile: version base image

README.md, cmd/backup/main.go, doc/user/download_backup.md, pkg/backup/backup.go, pkg/util/constants/constants.go, pkg/util/k8sutil/backup.go
fix https://github.com/coreos/etcd-operator/issues/692
=> backup: version backup dir on PV

CHANGELOG.md
We need to keep the change log after beta release.
Fix https://github.com/coreos/etcd-operator/issues/355
=> CHANGELOG: initial template

hack/test
=> test: enable race detector

pkg/cluster/cluster.go
update will return conflict if object is deleted
=> cluster: fix error check from update

test/e2e/restore_test.go
fix https://github.com/coreos/etcd-operator/issues/715.
See the discussion in #715 .
=> e2e: bump timeout for wait restore

pkg/cluster/backup_manager.go, pkg/cluster/cluster.go, pkg/garbagecollection/gc.go, pkg/util/k8sutil/backup.go
Fix https://github.com/coreos/etcd-operator/issues/615
=> cluster: let gc take care of removing k8s resources

pkg/util/k8sutil/backup.go
fix https://github.com/coreos/etcd-operator/issues/730
=> backup: inc pvc wait time to 60s

pkg/cluster/cluster.go, pkg/spec/cluster.go, test/e2e/basic_test.go, test/e2e/framework/framework.go
fix https://github.com/coreos/etcd-operator/issues/743
=> cluster: fix local status to not be pointer of cluster.status

test/e2e/framework/framework.go, test/e2e/util.go
trying to get more info for debugging issues:
- https://github.com/coreos/etcd-operator/issues/740
- https://github.com/coreos/etcd-operator/issues/738
=> e2e: print out pod's node name 

pkg/garbagecollection/gc.go
fix https://github.com/coreos/etcd-operator/issues/758
=> gc: collect failed pods

README.md
=> README: beta

test/e2e/basic_test.go, test/e2e/recovery_test.go, test/e2e/util.go
fix https://github.com/coreos/etcd-operator/issues/756
=> e2e: wait all members ready in waitSizeReached() 

client/experimentalclient/backup.go, pkg/cluster/reconcile.go, test/e2e/util.go
=> client/backup: allow specifying scheme

CHANGELOG.md, doc/dev/release.md, example/deployment-aws.yaml, example/deployment.yaml
=> example: use released version of operator

README.md
Fix https://github.com/coreos/etcd-operator/issues/485
/cc @hasbro17 @hongchaodeng
=> README: clarify that deletion of the operator will not delete etcd

CHANGELOG.md, pkg/spec/cluster.go, pkg/util/k8sutil/k8sutil.go, pkg/util/k8sutil/pod_util.go, pkg/util/k8sutil/self_hosted.go
fix https://github.com/coreos/etcd-operator/issues/307
=> spec: add resource requirements field

CHANGELOG.md, doc/user/backup_service.md, pkg/backup/backup.go, pkg/backup/backupapi/types.go, pkg/backup/file.go, pkg/backup/http.go, pkg/backup/s3.go, pkg/backup/s3_backend_test.go
/cc @hongchaodeng @hasbro17 
I am going to add a method to get the status in the backup client library.
=> backup: expose backup service status

pkg/cluster/cluster.go, pkg/cluster/self_hosted.go, pkg/cluster/upgrade.go, pkg/util/k8sutil/k8sutil.go, pkg/util/k8sutil/pod_util.go, pkg/util/k8sutil/self_hosted.go
=> *: follow go naming conventions

pkg/controller/controller.go, pkg/spec/cluster.go
=> controller: kill more inline consts

pkg/controller/controller.go
=> controller: rename monitor to watch

pkg/cluster/cluster.go, pkg/cluster/error.go, pkg/cluster/reconcile.go
=> cluster: minor cleanups

pkg/controller/controller.go, pkg/controller/util.go
=> controller: change event as const

client/cliente2e/Dockerfile, client/cliente2e/README.md, client/cliente2e/build, client/cliente2e/client_test.go, client/cliente2e/test, client/cmd/cliente2e/main.go, hack/jenkins
Trying to make the client self contained too.
=> client_e2e: in cluster test covering client

hack/test
hack/test: generate code coverage report
Creates coverage report to be consumed by codecov
#719 
=> hack/test: generate code coverage report

README.md
=> README: update k8s requirement to 1.5.3+

example/deployment-aws.yaml, example/deployment.yaml, version/version.go
=> release: v0.2.1

CHANGELOG.md, doc/dev/release.md
=> release: change CHANGELOG.md

doc/dev/release.md
=> docs: refine release to be step by step

CHANGELOG.md
=> CHANGELOG: update

pkg/spec/backup.go
=> spec: remove outdated todo

pkg/spec/cluster.go
=> spec: docs update

test/e2e/cluster_status_test.go
fix https://github.com/coreos/etcd-operator/issues/828
=> e2e: fix TestBackupStatus

doc/user/spec_examples.md
[skip ci]
fix https://github.com/coreos/etcd-operator/issues/752
=> doc: cluster spec examples

doc/user/spec_examples.md
=> doc: minor update on spec examples

hack/jenkins, hack/test
This helps us set up another jenkins for it separately.
=> test: refactor cliente2e as a test option

CHANGELOG.md
=> CHANGELOG.md: update

CHANGELOG.md, pkg/controller/controller.go, test/e2e/cluster_status_test.go, test/e2e/recovery_test.go, test/e2e/util.go
fix https://github.com/coreos/etcd-operator/issues/851
provide info for https://github.com/coreos/etcd-operator/issues/818
=> controller: check failed status before processing cluster event

README.md, cmd/operator/main.go, doc/user/backup_options.md
fix https://github.com/coreos/etcd-operator/issues/849
[skip ci]
=> docs: backup options setup guide

hack/ci/get_kube.sh
=> ci: mute untar message

doc/user/rbac.md
=> doc: update rbac version to v1beta1

README.md, doc/user/op_guide.md
fix https://github.com/coreos/etcd-operator/issues/735
[skip ci]
=> doc: op guide for install, uninstall etcd operator

README.md
Add badge for unit test
[skip ci]
=> README: update jenkins badge

CHANGELOG.md
=> CHANGELOG: self hosted hostpath change

CHANGELOG.md, example/deployment-aws.yaml, example/deployment.yaml, version/version.go
Update CHANGELOG and version for realease v0.2.2
[skip ci]
=> release:v0.2.2 CHANGELOG and version

version/version.go
=> version: bump to 0.2.2+git

doc/dev/developer_guide.md, doc/dev/release.md
=> docs: update release.md

doc/dev/release.md
=> doc: Update release.md

doc/dev/release.md, doc/user/backup_options.md
=> doc: fix typos in release.md and backup_options.md

doc/user/cluster_tls.md, pkg/spec/cluster.go, pkg/spec/cluster_tls.go
=> spec: add cluster tls configuration

CHANGELOG.md
=> CHANGELOG: tlsspec omitempty

hack/build/operator/build
Cross compiling fails on Mac. Fixed the build script to work on Mac.
=> Fixed the build script to work on Mac

doc/dev/developer_guide.md
Not necessary to run on linux only.
=> doc: update developer_guide.md

CHANGELOG.md, README.md, doc/user/spec_examples.md, example/example-etcd-cluster-with-backup.yaml, example/example-etcd-cluster.yaml, pkg/spec/cluster.go, test/e2e/basic_test.go
There is a hang process issue being fixed:
https://github.com/coreos/etcd/issues/7512
=> *: update default etcd version to 3.1.4

doc/user/backup_config.md
fix https://github.com/coreos/etcd-operator/issues/924
[skip ci]
=> docs: refine S3 backup section

pkg/spec/backup.go, pkg/spec/cluster.go
fix https://github.com/coreos/etcd-operator/issues/929
=> backup: check zero volume size

pkg/backup/backup.go, pkg/cluster/cluster.go, pkg/cluster/member.go, pkg/cluster/reconcile.go, pkg/util/etcdutil/etcdutil.go, pkg/util/etcdutil/member.go
fix https://github.com/coreos/etcd-operator/issues/901
=> cluster: use fqdn as url

CHANGELOG.md
depends on https://github.com/coreos/etcd-operator/pull/937
[skip ci]
=> CHANGELOG: update hostname and subdomain change

doc/user/backup_service.md
[skip ci]
For issues like #941 
=> docs: mention that backup is skipped

pkg/backup/backend.go, pkg/backup/backup.go, pkg/backup/file.go, pkg/backup/file_backend_test.go, pkg/backup/http.go, pkg/backup/s3.go
fix https://github.com/coreos/etcd-operator/issues/942
=> backup: avoid making the same backup on restart

pkg/backup/backup.go, pkg/backup/s3/s3.go, pkg/backup/s3_backend_test.go
- make prefix path more deterministic
- randString() should not return "/"
=> s3: some code correction

doc/user/download_backup.md
=> doc: update download_backup.md

test/e2e/e2eutil/tls.go, test/e2e/restore_test.go, test/e2e/tls_test.go
Add a test for https://github.com/coreos/etcd-operator/pull/939 . See second commit.
=> e2e: add tls test

CHANGELOG.md, doc/best_practices.md, pkg/spec/cluster.go, pkg/util/k8sutil/k8sutil.go, pkg/util/k8sutil/self_hosted.go
@hongchaodeng @hasbro17 PTAL
/cc @aaronlevy
=> *: add Tolerations on pod

pkg/cluster/upgrade.go, pkg/util/k8sutil/k8sutil.go
fix https://github.com/coreos/etcd-operator/issues/966
/cc @hongchaodeng @aaronlevy
=> cluster: use patch instead of update to patch a pod object

doc/user/cluster_tls.md
=> docs: update tls user guide

example/deployment-aws.yaml
=> example: add errexit

pkg/util/k8sutil/pod_util.go
=> pkg/util/k8sutil: use v1.Affinity instead of alpha annotation

doc/user/cluster_tls.md
=> doc: update cluster_tls.md

README.md
[skip-ci]
Make the resize example in the README simpler with `kubectl apply` instead of posting json via curl.
=> README: Use kubectl apply for resize example

CHANGELOG.md, example/deployment-aws.yaml, example/deployment-s3-backup.yaml.template, example/deployment.yaml, version/version.go
=> release: v0.2.5

version/version.go
=> version: bump to 0.2.5+git

MAINTAINERS
=> MAINTAINERS: add hasbro17 as maintainer

README.md
The client service endpoints have changed since v0.2.5
[skip ci]
=> README: change client service endpoint

doc/user/download_backup.md
=> docs: update download_backup.md

CHANGELOG.md, pkg/util/k8sutil/pod_util.go, pkg/util/k8sutil/self_hosted.go
fix https://github.com/coreos/etcd-operator/issues/978
=> selfHosted: fix anti-affinity

pkg/cluster/member.go
this should help debugging https://github.com/coreos/etcd-operator/issues/978
=> cluster: detect bad member in self hosted case

pkg/spec/cluster.go, pkg/util/k8sutil/k8sutil.go, pkg/util/k8sutil/pod_util.go, pkg/util/k8sutil/self_hosted.go
fix https://github.com/coreos/etcd-operator/issues/914.
=> spec: support user defined evn

CHANGELOG.md, pkg/spec/cluster.go, pkg/util/k8sutil/k8sutil.go, pkg/util/k8sutil/self_hosted.go
fix https://github.com/coreos/etcd-operator/issues/872
/cc @hongchaodeng @hasbro17
=> *: support customized labels

doc/user/cluster_tls.md, pkg/spec/cluster.go, pkg/util/etcdutil/member.go, pkg/util/k8sutil/k8sutil.go, pkg/util/k8sutil/pod_util.go
close https://github.com/coreos/etcd-operator/pull/971
=> k8sutil: TLS option in etcd pod

README.md
=> README: fix client service

hack/test, test/e2e/upgradetest/README.md, test/e2e/upgradetest/framework/framework.go, test/e2e/upgradetest/main_test.go
This is to implement https://github.com/coreos/etcd-operator/issues/989#issuecomment-297906941
=> upgradetest: add framework for operator deploy

hack/test
- indent
- combine two list packages into one var
=> hack/test: clean up

pkg/util/k8sutil/k8sutil.go, pkg/util/k8sutil/pod_util.go, pkg/util/k8sutil/self_hosted.go
/cc @hongchaodeng 
prepare for adding pod policy into backup sidecar.
=> k8sutil: move pod policy handling into one place

doc/dev/developer_guide.md
=> doc: update go version to 1.8+

doc/user/cluster_tls.md
=> doc: update links to self-signed TLS tutorial

pkg/cluster/backup_manager.go, pkg/spec/backup.go, pkg/spec/cluster.go, pkg/util/k8sutil/backup.go, pkg/util/k8sutil/pod_util.go, pkg/util/k8sutil/self_hosted.go
=> *: add pod policy to backup pod

CHANGELOG.md
[skip ci]
close https://github.com/coreos/etcd-operator/issues/1000
=> CHANGELOG: add TLS

CHANGELOG.md, example/deployment-aws.yaml, example/deployment-s3-backup.yaml.template, example/deployment.yaml, version/version.go
=> release: 0.2.6

version/version.go
=> version: bump 0.2.6+git

doc/user/op_guide.md
Fixes #1040.
Signed-off-by: Ahmet Alp Balkan <ahmetb@google.com>
[skip ci]
=> Document installation via helm chart

pkg/backup/backup.go, pkg/backup/s3/s3.go, pkg/backup/s3_backend_test.go, pkg/cluster/backupstorage/s3.go, test/e2e/e2eutil/wait_util.go
We have exposed dir layout in e2e test code.
We need to refactor existing translator layer code and hide it.
=> s3: refactor New() logic and hide internal dir layout

README.md
=> README: link to client-service doc

README.md
=> README: fix link to client_service.md

test/e2e/upgradetest/framework/framework.go, test/e2e/upgradetest/upgrade_test.go
1. should defer delete operator after create
2. reduce grace period
=> upgrade_test: fix delete operator

test/e2e/cluster_status_test.go, test/e2e/e2eutil/util.go, test/e2e/recovery_test.go, test/e2e/restore_test.go, test/e2e/util.go
First commit from https://github.com/coreos/etcd-operator/pull/1065
=> e2eutil: port WaitBackupPod() and MakeBackup()

CHANGELOG.md, pkg/util/k8sutil/backup.go
fix https://github.com/coreos/etcd-operator/issues/1068
=> backup: change deployment update strategy to Recreate

pkg/cluster/backup_manager.go
This is for BC of v0.2.6 . Ref: https://github.com/coreos/etcd-operator/issues/1046#issue-226070611 .
I have manually tested this for upgrade test in https://github.com/coreos/etcd-operator/pull/1067 . It will pass only with this patch.
=> cluster: upgrade backup sidecar should also change it to use Recreate strategy

pkg/spec/backup.go
/cc @hongchaodeng @hasbro17 
[skip ci]
=> spec: add s3 configuration into s3 source

pkg/spec/cluster.go
Fix https://github.com/coreos/etcd-operator/issues/868
=> spec: add doc for field updates

doc/user/backup_service.md, pkg/backup/backup.go, pkg/backup/http.go
fix https://github.com/coreos/etcd-operator/issues/1018
=> backup: write backup status as http response

pkg/controller/controller.go, pkg/controller/metrics.go
=> controller: add failed cluster metrics

test/e2e/upgradetest/upgrade_test.go
Added `TestDisasterRecovery()` to test if the upgraded operator can do disaster recovery from the backup of the old cluster once all its pods are deleted.
=> upgradetest: Add disaster recovery test

CHANGELOG.md, pkg/backup/s3/s3.go, pkg/cluster/backup_manager.go, pkg/cluster/backupstorage/s3.go, pkg/controller/s3.go, pkg/spec/backup.go, pkg/util/k8sutil/backup.go, test/e2e/e2eutil/spec_util.go, test/e2e/framework/framework.go, test/e2e/recovery_test.go, test/e2e/restore_test.go, test/e2e/upgradetest/upgrade_test.go
fix https://github.com/coreos/etcd-operator/issues/923
=> *: per cluster s3 policy

doc/user/backup_service.md, doc/user/upgrade/incompatible_upgrade.md, doc/user/upgrade/upgrade_guide.md
[skip ci]
@xiang90 @hongchaodeng PTAL to see if this is the format and level of detail expected in the upgrade guide.
For operations like creating and restoring from a backup, I've only given a general description and linked to the other docs where it's explained in more detail. I can be more explicit here if required.
=> doc: add upgrade guide

README.md, doc/user/upgrade/upgrade_guide.md
=> README: link to upgrade guide

CHANGELOG.md, example/deployment-aws.yaml, example/deployment-s3-backup.yaml.template, example/deployment.yaml, version/version.go
=> release: v0.3.0

version/version.go
=> version: bump to 0.3.0+git

doc/user/cluster_tls.md
fix https://github.com/coreos/etcd-operator/issues/1099
[skip ci]
=> doc: update TLS for how to access cluster

doc/dev/developer_guide.md
=> developer_guide: mention explicitly the GOPATH dir

pkg/spec/cluster.go, pkg/spec/cluster_tls.go, pkg/spec/self_hosted.go
Many son fields doesn’t need to be there if empty.
=> spec: add `omitempty`

pkg/backup/backup.go, pkg/cluster/cluster.go, pkg/cluster/member.go, pkg/cluster/reconcile.go, pkg/cluster/self_hosted.go, pkg/util/etcdutil/member.go, pkg/util/k8sutil/k8sutil.go, pkg/util/k8sutil/pod_util.go, pkg/util/k8sutil/self_hosted.go, test/e2e/self_hosted_test.go
fix https://github.com/coreos/etcd-operator/issues/1102
=> selfHosted: use FQDN for client/peer communication

CHANGELOG.md, pkg/util/k8sutil/self_hosted.go, test/e2e/e2eslow/self_hosted_test.go, test/e2e/e2eslow/tls_test.go
fix https://github.com/coreos/etcd-operator/issues/1010
=> Self-hosted etcd TLS

CHANGELOG.md, doc/user/upgrade/upgrade_guide.md
=> CHANGELOG: add FQDN update on self-hosted

cmd/operator/main.go
Our operator was not recording anything before. Fixing it to use event
recorder.
=> leader_election: use event recorder

CHANGELOG.md, client/experimentalclient/backup.go, doc/user/backup_service.md, pkg/backup/backup.go, pkg/backup/backup_test.go, pkg/backup/backupapi/http.go, pkg/backup/backupapi/types.go, pkg/backup/http.go, pkg/spec/backup.go, pkg/util/k8sutil/k8sutil.go
fix https://github.com/coreos/etcd-operator/issues/1079
=> *: allow getting a specified backup

CHANGELOG.md
=> CHANGELOG: add notes on breaking change for SelfHosted

pkg/backup/backup_test.go
=> backup_test: renaming test for understandability

version/version.go
=> *: bump version to 0.3.1+git

CHANGELOG.md, example/deployment-aws.yaml, example/deployment-s3-backup.yaml.template, example/deployment.yaml, version/version.go
=> release: 0.3.2

version/version.go
=> *: bump version to 0.3.2+git

test/e2e/upgradetest/framework/framework.go
Period increased to 10s to reduce polling frequency of readiness probe.
[skip ci]
=> upgradetest: change readiness probe period

pkg/cluster/self_hosted.go
fix https://github.com/coreos/etcd-operator/issues/1138
Remove the infinite wait loop in add self hosted member. Instead, we
trigger another updateMembers() in most cases where the reconcile
interval should be enough.
In extreme case, the new pod won’t be recognized in the quorum. We
tolerate such unknown members for 60s and then delete them.
=> selfHosted: unblock adding member for scheduling issue

CHANGELOG.md
=> CHANGELOG: fix operator stuck in adding self hosted member

pkg/cluster/self_hosted.go
Continuing the conversation in https://github.com/coreos/etcd-operator/pull/1177#issuecomment-307257807 .
We need to make sure a pod wasn’t bound to any node and make sure the add member won’t be run.
=> selfHosted: safety checks on node binding if adding new member failed

pkg/cluster/cluster.go
fixes #1199 
The cluster struct's spec/status fields are encoded and logged in json format.
The new output looks like the following:
Cluster creation:
```
time="2017-06-21T19:16:11Z" level=info msg="creating cluster with
Spec:
{
"size": 3,
"baseImage": "quay.io/coreos/etcd",
"version": "3.1.7"
}
Status:
{
"phase": "Creating",
"reason": "",
"controlPaused": false,
"conditions": null,
"size": 0,
"members": {},
"currentVersion": "",
"targetVersion": ""
}" cluster-name=example-etcd-cluster pkg=cluster
time="2017-06-21T19:16:11Z" level=info msg="cluster created with seed member (example-etcd-cluster-0000)" cluster-name=example-etcd-cluster pkg=cluster
```
Spec Update:
```
time="2017-06-21T19:17:07Z" level=info msg="Finish reconciling" cluster-name=example-etcd-cluster pkg=cluster …
```
=> pkg/cluster: make cluster struct printing more readable

pkg/cluster/backupstorage/s3.go
ref: https://github.com/coreos/etcd-operator/issues/1196
=> operator: put s3 config under $HOME/etc

CHANGELOG.md
=> CHANGELOG: add fix for S3 backup problem in non-root user

CHANGELOG.md, example/deployment-aws.yaml, example/deployment-s3-backup.yaml.template, example/deployment.yaml, version/version.go
=> release: v0.3.3

version/version.go
=> version: bump 0.3.3+git

hack/test
codecov is down. But it shouldn’t affect our test pass.
=> hack/test: codecov down shouldn't affect test pass

CHANGELOG.md
=> CHANGELOG: add autoDelete change

CHANGELOG.md, example/deployment-aws.yaml, example/deployment-s3-backup.yaml.template, example/deployment.yaml, version/version.go
=> release: v0.4.0

version/version.go
=> version: bump to 0.4.0+git

hack/ci/get_kube.sh
=> ci: add params

pkg/cluster/reconcile.go, pkg/util/etcdutil/etcdutil.go
=> 	*: wrap error when clientv3.New() fail

CHANGELOG.md, pkg/cluster/self_hosted.go, pkg/spec/self_hosted.go
=> Add SkipBootMemberRemoval to self-hosted spec

pkg/cluster/cluster.go
Some e2e tests are failing because the membership is updated too late. Everything else is running correctly. We should update status with latest membership anyway.
=> cluster: update status with latest membership

CHANGELOG.md, README.md, example/deployment-aws.yaml, example/deployment-s3-backup.yaml.template, example/deployment.yaml, version/version.go
=> release: v0.4.1

version/version.go
=> version: bump to 0.4.1+git

pkg/cluster/backupstorage/s3.go
In reference to #1221.  This makes the secret and the 2 configurations under the secret optional.
This makes the secrets for configuration optional.  A few valid configurations would be.
* Create the secret for both credentials and config (Current method)
* Use AWS IAM instance profile with the config for aws region
* Use AWS IAM instance profile with an alternative aws region method such as AWS_REGION or AWS_DEFAULT_REGION environment variables.
@hongchaodeng
=> adds support for using aws IAM credentials

pkg/backup/s3/s3.go, pkg/cluster/backupstorage/s3.go
fix https://github.com/coreos/etcd-operator/issues/1200
=> S3_storage: wrap errors in return

test/e2e/e2eutil/wait_util.go
Fix the e2e test `TestEtcdUpgrade` to detect the version upgrade failure from #1211 by checking that the etcd pods are Running and their container status images are updated to the desired version.
With no fix for #1211 the test `TestEtcdUpgrade` should now fail.
=> e2eutil/wait_util: check container status version instead of TPR version

CHANGELOG.md
=> CHANGELOG: add tolerate unready endpoints

CHANGELOG.md, example/deployment-aws.yaml, example/deployment-s3-backup.yaml.template, example/deployment.yaml, version/version.go
=> release: v0.4.2

version/version.go
=> version: bump to 0.4.2+git

glide.lock, glide.yaml
fix https://github.com/coreos/etcd-operator/issues/1273
=> vendor: client-go v4.0.0-beta and other updates

doc/user/backup_config.md
=> backup_config.md: add aws iam note

doc/user/spec_examples.md
=> spec_examples.md: refer to backup_config.md

doc/user/rbac.md, hack/ci/rbac_utils.sh
Change rbac rule from TPR->CRD in rbac_utils and the rbac guide doc.
=> rbac: change rules for CRD

pkg/spec/cluster.go
=> spec: update comment since TLS is done

CHANGELOG.md, example/deployment-aws.yaml, example/deployment-s3-backup.yaml.template, example/deployment.yaml, version/version.go
=> release: 0.5.0

version/version.go
=> version: bump to 0.5.0+git

doc/user/backup_config.md, pkg/spec/backup.go
Subset of #1358 implementing just spec field and docs.
=> Add StorageClass spec and docs

CHANGELOG.md, example/deployment-aws.yaml, example/deployment-s3-backup.yaml.template, example/deployment.yaml, version/version.go
=> release: 0.5.1

version/version.go
=> version: bump to 0.5.1+git

doc/design/abs_backup.md, doc/dev/testing/azure.md, doc/user/backup_config.md, doc/user/spec_examples.md, pkg/spec/backup.go
Ref https://github.com/coreos/etcd-operator/pull/1237
[skip ci]
=> feat(abs): add docs, design, spec

glide.lock, glide.yaml, pkg/backup/abs.go, pkg/backup/abs/abs.go, pkg/backup/backup.go, pkg/backup/env/env.go, pkg/spec/backup.go
Ref https://github.com/coreos/etcd-operator/pull/1237
=> feat(abs): add backup sidecar logic

pkg/backup/abs/absconfig/abs_ctx.go, pkg/cluster/backup_manager.go, pkg/cluster/backupstorage/abs.go, pkg/cluster/cluster.go, pkg/spec/backup.go, pkg/util/k8sutil/backup.go
Ref https://github.com/coreos/etcd-operator/pull/1237
[skip ci]
=> feat(abs): add operator logic

pkg/backup/backup.go, pkg/backup/backupapi/api.go, pkg/backup/backupapi/http.go, pkg/backup/s3.go, pkg/backup/s3/s3.go, pkg/backup/s3_backend_test.go, pkg/cluster/backupstorage/s3.go, pkg/spec/backup.go
=> backup: add support for s3 path prefix configuration

doc/user/backup_config.md, doc/user/download_backup.md
=> doc: add support for s3 prefix in doc

CHANGELOG.md
=> CHANGELOG: add metrics and s3 prefix change

CHANGELOG.md, cmd/operator/main.go, doc/user/backup_config.md
=> api: deprecate s3 operator flag

cmd/operator/main.go, glide.lock, glide.yaml, pkg/client/cr.go, pkg/cluster/cluster.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/informer.go, pkg/controller/util.go, pkg/spec/cluster.go, pkg/util/k8sutil/crd.go, test/e2e/basic_test.go, test/e2e/cluster_status_test.go, test/e2e/e2esh/self_hosted_test.go, test/e2e/e2eslow/disruptive_test.go, test/e2e/e2eslow/tls_util.go, test/e2e/e2eutil/wait_util.go, test/e2e/recovery_test.go, test/e2e/resize_test.go, test/e2e/restore_test.go, test/e2e/upgradetest/upgrade_test.go
Now CRD has good informer example and support from upstream.
We change to use it.
=> controller: change to use informer

test/e2e/upgradetest/upgrade_test.go
[skip ci]
Urgent fix for upgrade test compile failure
=> upgradetest: fix compile

doc/dev/testing/azure.md, pkg/backup/abs_backend_test.go, pkg/cluster/backup_manager_test.go
Ref https://github.com/coreos/etcd-operator/pull/1237
=> feat(abs): add tests

version/version.go
=> version: bump to 0.5.2+git

doc/user/spec_examples.md
=> doc: clarify s3 backup with restore spec

doc/user/upgrade/upgrade_guide.md
=> doc: add v0.5.x -> v0.6.0 update steps

pkg/apis/etcd/v1beta2/doc.go, pkg/apis/etcd/v1beta2/register.go
=> apis: minor change for codegen

hack/k8s/codegen/Dockerfile, hack/k8s/codegen/codegen.sh, hack/k8s/codegen/run_in_docker.sh, hack/k8s/codegen/update-generated.sh
all: clientset, informer, lister
=> hack: add codegen script for all

doc/user/conditions_and_events.md
[skip ci]
Define Events #1412
Refine conditions #1388
=> doc: events for EtcdCluster proposal

hack/test
Also rewrite find_files() to make it aligned with search packages.
=> hack/test: fix gosimple check, rewrite to make list pkgs and files consistent

CHANGELOG.md, example/deployment-aws.yaml, example/deployment.yaml, version/version.go
=> release: 0.6.0

version/version.go
=> version: bump to 0.6.0+git

doc/design/backup_operator.md
=> doc: backup operator design doc

hack/k8s/codegen/README.md, hack/k8s/codegen/run_in_docker.sh
=> codegen: add README

test/e2e/upgradetest/framework/framework.go
=> upgradetest/framework: Add reason for deleting Endpoints resource

doc/dev/debug_e2e_flake.md
=> doc: debug e2e flake

test/e2e/e2eutil/wait_util.go, test/e2e/recovery_test.go
Print more info for waiting backup pod
=> 	 test: add logging to wait backup up

hack/build/etcd-backup-operator/build, pkg/etcd-backup-operator/controller/operator.go, test/e2e/framework/framework.go
Help debug https://github.com/coreos/etcd-operator/issues/1483
=> e2e: debug etcd operator setup problem

doc/user/resource_labels.md
=> doc: refine resources doc

pkg/backup/backend/abs.go, pkg/backup/backend/abs_backend_test.go, pkg/backup/backend/backend.go, pkg/backup/backend/file.go, pkg/backup/backend/file_backend_test.go, pkg/backup/backend/s3.go, pkg/backup/backend/s3_backend_test.go, pkg/backup/backup.go, pkg/backup/backup_test.go, pkg/backup/http.go, pkg/backup/util/constants.go, pkg/backup/util/util.go, pkg/backup/util/util_test.go
expose backend interface and backend objects. 
refactor any backend related files into backup/backend dir.
=> *: expose backend and refactor backend files

doc/best_practices.md, doc/design/cluster_status.md
Sorry for another PR to fix broken link. 
I'm learning the etcd-operator's design to improve my operator project. The `doc/design` gives me much new thinking :D
[skip ci]
=> doc/*: fix `k8s tainted` broken link

pkg/etcd-backup-operator/controller/s3_backup.go, pkg/etcd-backup-operator/controller/sync.go
add handleBackup function which choose backup handler based on the passed in backup type.
add handleS3 handler which performs s3 specific backup.
=> etcd-backup-operator/controller: handle backup

example/etcd-backup-operator/backup.yaml, example/etcd-backup-operator/crd.yaml, example/etcd-backup-operator/deploy.yaml
=> examples: add etcd backup operator example yaml files

doc/design/backup_operator.md, doc/design/restore_operator.md
=> doc: restore operator design

pkg/etcd-backup-operator/controller/sync.go
reportBackupStatus method updates backup status to backup CR
fixes https://github.com/coreos/etcd-operator/issues/1494
=> etcd-backup-operator/controller: add reportBackupStatus

pkg/apis/etcd/v1beta2/etcd_restore_types.go, pkg/apis/etcd/v1beta2/zz_generated.deepcopy.go
fixes type in EtcdRestoreList.
=> apis: EtcdRestoreList uses EtcdRestore instead EtcdBackup

cmd/etcd-restore-operator/main.go, version/etcd-restore-operator/version.go
add etcd restore operator main.go.
add etcd restore operator version.
this pr adds the entry point of etcd restore operator.
=> *: add etcd restore operator main.go

cmd/etcd-restore-operator/main.go, pkg/controller/restorecontroller/controller.go, pkg/controller/restorecontroller/operator.go, pkg/controller/restorecontroller/sync.go
add controller portion of etcd-restore-operator.
this is a framework for setting up receiving/retry restore CR request.
=> etcd-restore-operator: add etcd-restore-operator controller

cmd/backup/main.go, pkg/backup/backup.go, pkg/backup/http.go
Reverts coreos/etcd-operator#1523
=> Revert "*: expose startHTTP"

doc/design/restore_operator.md
=> design: ownerref mgmt of seed member pod in restore

pkg/controller/backup-operator/operator.go, pkg/controller/restore-operator/operator.go
Not used anywhere.
Not going to create CRD inside operator.
=> *: remove kube ext client

pkg/backup/backupapi/http.go, pkg/cluster/cluster.go, pkg/util/k8sutil/k8sutil.go
operator to use to create seed member
=> *: refactor NewSeedMemberPod() and BackupURLForCluster() for restore

CHANGELOG.md
=> CHANGELOG: add recent change on cluster resource

CHANGELOG.md, example/deployment-aws.yaml, example/deployment.yaml, version/version.go
=> *: release 0.6.1, bump version, update CHANGELOG

pkg/apis/etcd/v1beta2/restore_types.go, pkg/controller/restore-operator/sync.go
TODO: Manual test creation of seed member. Expect the seed member should start with a backup.
=> controller/restore-operator: create seed member 

hack/build/backup-operator/build, hack/build/operator/build, hack/build/restore-operator/build
=> build: add GOINSTALL option

pkg/controller/restore-operator/sync.go
move the responsibility of creating CreateClientService to etcd operator.
=> controller/restore-operator: remove CreateClientService

README.md, doc/user/install_guide.md, example/rbac/create_role.sh
=> *: doc improvement

pkg/controller/restore-operator/operator.go
let restore operator creates the crd it needs when starting. 
In this way, user doesn't have to create the crd beforehand.
=> controller/restore-operator: init crd when starting restore operator

pkg/apis/etcd/v1beta2/backup_types.go, pkg/apis/etcd/v1beta2/restore_types.go
=> api: restore from S3Path

README.md
=> README: fix broken link to install guide

pkg/backup/reader/s3_reader.go, pkg/backup/util/util.go, pkg/backup/writer/s3_writer.go, pkg/backup/writer/writer.go
expose parseBucketAndKey so that writer can also parse s3 path into bucket and key.
add writer interface/impl.
=> *: add backup writer

pkg/backup/backup_manager.go
refactor get max member and its client into a method called etcdClientWithMaxRevision.
=> backup: add etcdClientWithMaxRevision

pkg/backup/backup.go
fix https://github.com/coreos/etcd-operator/issues/1613
=> backup: fix index out of range

cmd/backup-operator/README.md
add backup operator readme.
[skip ci]
=> readme: add backup operator readme

example/etcd-restore-operator/restore_cr.yaml
=> examples: update restore CR

cmd/backup-operator/README.md, example/etcd-backup-operator/backup_cr.yaml
[skip ci]
Added a cleanup section and renamed the backup CR to distinguish it from the cluster name.
=> *: update backup README and cr

cmd/restore-operator/README.md
=> cmd/restore-operator: add README

cmd/backup-operator/README.md
=> backup-operator/README: minor change

test/e2e/upgradetest/framework/framework.go
setupAWS, S3Cli, and S3Bucket are not used anywhere in e2e upgradetest. 
they should be removed.
=> e2e/upgradetest: remove setupAWS, S3Cli, and S3Bucket

test/pod/Dockerfile, test/pod/README.md, test/pod/build, test/pod/run-test-pod, test/pod/test, test/pod/test-pod.yaml
[skip ci]
Added some scripts and a REAME to show how to run the e2e tests inside a pod.
/cc @fanminshi @hongchaodeng PTAL and try out the README.
=> test/pod: add scripts for running e2e tests in a pod

hack/build/operator/Dockerfile, hack/build/operator/build
operator build should only build operator binary not pushing it.
=> hack: remove push from operator build

README.md
=> readme: remove reference to old backup/restore

README.md
=> readme: add restore/backup walkthrough to readme

doc/user/install_guide.md
=> install_guide: add disclaimer for helm chart

doc/user/install_guide.md
=> install_guide: fix disclaimer

CHANGELOG.md
=> changelog: update change log for 0.7.0 release

CHANGELOG.md, example/deployment.yaml, example/etcd-backup-operator/deployment.yaml, example/etcd-restore-operator/deployment.yaml, version/version.go
=> *: release 0.7.0, bump version, update CHANGELOG

version/version.go
=> version: +git version bump

doc/dev/release.md
=> doc/dev: fix push step in release doc

pkg/cluster/cluster.go, pkg/util/etcdutil/etcdutil.go, pkg/util/util.go, test/e2e/e2eutil/wait_util.go
=> *: remove explicit health check

test/pod/run-test-pod
[skip ci]
ref: #1640 
Open to any opinions on making the logfile name/location configurable.
=> test/pod: save test-pod logs to file

pkg/cluster/cluster.go, pkg/cluster/member.go, pkg/cluster/self_hosted.go, pkg/util/etcdutil/member.go, pkg/util/k8sutil/pod_util.go, pkg/util/k8sutil/self_hosted.go
First step for #1644 
/cc @hongchaodeng @hasbro17
=> Use podIPs rather than DNS hostnames

pkg/cluster/cluster.go, pkg/cluster/member.go, pkg/cluster/self_hosted.go, pkg/util/etcdutil/member.go, pkg/util/k8sutil/pod_util.go, pkg/util/k8sutil/self_hosted.go
Reverts coreos/etcd-operator#1662
=> Revert "Use podIPs rather than DNS hostnames"

test/e2e/e2eslow/tls_test.go
TestTLS now uses `PrepareTLS` and `ClusterCRWithTLS` to create etcd tls secret and to attach TLS policy to `ClusterCR`.
=> e2eslow: refactor tls_test.go

doc/user/client_service.md
=> docs: client-service editorial pass

doc/user/install_guide.md
=> docs: editorial pass on install_guide.md

doc/user/spec_examples.md
=> docs: editorial pass for spec_examples.md

doc/user/resource_labels.md
=> docs: editorial pass for resource_labels.md

doc/user/conditions_and_events.md
=> docs: editorial pass on conditions_and_events.md

doc/user/cluster_tls.md
=> docs: change 'etcd-operator' to 'etcd operator'

doc/user/rbac.md
=> docs: editorial pass for rbac.md

hack/build/Dockerfile
fix https://github.com/coreos/etcd-operator/issues/806
=> docker: set user `etcd-operator`

CHANGELOG.md
=> CHANGELOG: make up missing records

hack/ci/run, hack/lib/build.sh, hack/lib/test_lib.sh, hack/test, hack/unit_test
ref: https://github.com/coreos/etcd-operator/issues/1640
=> hack: containerize unit test

hack/test, test/e2e/framework/framework.go, test/logcollector/main.go, test/pod/test-pod.yaml
ref: https://github.com/coreos/etcd-operator/issues/1640
- Set parallelization in e2e
- Combine all three operators in one pod
=> *: improve pod testing performance

CHANGELOG.md, README.md, example/etcd-restore-operator/restore_cr.yaml, pkg/apis/etcd/v1beta2/cluster.go, pkg/cluster/upgrade.go, pkg/util/k8sutil/k8sutil.go, pkg/util/k8sutil/pod_util.go, pkg/util/k8sutil/self_hosted.go, test/e2e/basic_test.go, test/e2e/e2eutil/spec_util.go
ref: https://github.com/coreos/etcd-operator/issues/1719
fix https://github.com/coreos/etcd-operator/issues/1675
=> ClusterSpec: rename BaseImage to Repository

CHANGELOG.md, doc/user/spec_examples.md, pkg/apis/etcd/v1beta2/cluster.go, pkg/apis/etcd/v1beta2/zz_generated.deepcopy.go, pkg/controller/controller.go, pkg/controller/restore-operator/sync.go, pkg/util/k8sutil/pod_util.go, pkg/util/k8sutil/self_hosted.go
Fix https://github.com/coreos/etcd-operator/issues/1676
=> ClusterSpec: add generic Affinity and deprecate bool AntiAffinity

hack/k8s/codegen/Dockerfile
=> hack: remove outdated comment

doc/dev/developer_guide.md, doc/dev/release.md, hack/lib/build.sh
=> 	 doc: update developer_guide

CHANGELOG.md, example/deployment.yaml, example/etcd-backup-operator/deployment.yaml, example/etcd-restore-operator/deployment.yaml, version/version.go
=> release: 0.7.1

CHANGELOG.md, example/deployment.yaml, example/etcd-backup-operator/deployment.yaml, example/etcd-restore-operator/deployment.yaml, version/version.go
=> release: 0.7.2

version/version.go
=> *: bump version to v0.7.2+git

hack/build/e2e/builder/Dockerfile, hack/fmt_pass, hack/test
ref: https://github.com/coreos/etcd-operator/issues/1640
=> hack: containerize fmt_pass

pkg/controller/restore-operator/sync.go
add spec validation in restore operator.
=> controller: add cluster spec validation in restore operator

pkg/apis/etcd/v1beta2/backup_types.go
=> api: add justification for fields

doc/user/walkthrough/backup-operator.md, doc/user/walkthrough/restore-operator.md, example/etcd-backup-operator/backup_cr.yaml, pkg/apis/etcd/v1beta2/backup_types.go, pkg/apis/etcd/v1beta2/restore_types.go
=> *: fix doc for s3Path and randomize test

doc/user/walkthrough/backup-operator.md, example/etcd-backup-operator/backup_cr.yaml
change backup operator walkthrough to use etcdEndpoints.
[skip ci]
=> *: modify doc to on supporting endpoints in backup spec

pkg/backup/backup_manager.go
Since getEndpointWithMaxRev already creates etcdclient in order to determine the endpoint with max rev, it can smartly return the etcdclient with max rev instead. 
Then backupmanager can use that client directly to retrieve snapshot instead of create a new client based on the max rev endpoint that getEndpointWithMaxRev originally returns.
=> pkg/backup: change getEndpointWithMaxRev to getClientWithMaxRev

cmd/backup-operator/main.go, pkg/controller/backup-operator/operator.go
add create-crd flag allowing user to return off automatic crd creation by etcd backup operator.
=> *: add create-crd flag to etcd backup operator

doc/user/walkthrough/backup-operator.md
add etcdRevision and etcdVersion to the backup status section in backup-operator.md
[skip ci]
=> doc: add etcdRevision and etcdVersion in backup-operator.md walkthrough

doc/user/walkthrough/restore-operator.md
[skip ci]
fix https://github.com/coreos/etcd-operator/issues/1770
Check the doc. This is the only thing that needs to change.
=> doc: fix restore operator walkthrough

doc/user/install_guide.md
=> install_guide: add Alejandro Escobar as the maintainer for helm chart

test/container/run
=> test/container: set default KUBECONFIG

test/container/run
=> test/container: show nodes

doc/user/walkthrough/backup-operator.md, example/etcd-backup-operator/backup_cr.yaml
=> example/backup: make etcdEndpoints array less confusing

pkg/controller/restore-operator/sync.go, test/e2e/e2eslow/backup_restore_test.go, test/e2e/resize_test.go
fix https://github.com/coreos/etcd-operator/issues/1812
=> restore: force delete resources instead of waiting

example/etcd-backup-operator/backup_cr.yaml, example/etcd-restore-operator/restore_cr.yaml
It need to include backupStorageType.
[skip ci]
=> example: fix restore_cr

pkg/backup/backup_manager.go
=> pkg/backup: better error output in getClientWithMaxRev

CHANGELOG.md
=> CHANGELOG: add readiness probe change

CHANGELOG.md
Add major changes to the CHANGELOG from 0.7.2 tag to current master.
[skip ci]
=> CHANGELOG: add changes between 0.7.2 to current master

CHANGELOG.md, example/deployment.yaml, example/etcd-backup-operator/deployment.yaml, example/etcd-restore-operator/deployment.yaml, version/version.go
=> release: v0.8.0

version/version.go
=> version: bump version to 0.8.0+git

test/pod/run-test-pod
help debug https://github.com/coreos/etcd-operator/issues/1825
=> jenkins: describe e2e testing pod when it failed

code-of-conduct.md
=> automated PR: update CoC

hack/ci/run_e2e, hack/ci/run_unit
fix https://github.com/coreos/etcd-operator/issues/1831
=> hack: fix jenkins delete workspace

MAINTAINERS
[skip ci]
Fanmin has been actively contributing and maintaining this project. Thanks Fanmin for the great and hard work!
=> MAINTAINER: add Fanmin Shi

pkg/controller/restore-operator/sync.go
The `if er.Name != er.Spec.EtcdCluster.Name {` path is dismissed in reportError() path.
=> restore-operator: fix dismissed path to report error

CHANGELOG.md
=> CHANGELOG: add report error fix

hack/release/bump_version.sh
=> hack/release: add automate bump-up script

CHANGELOG.md, doc/dev/release.md, example/deployment.yaml, example/etcd-backup-operator/deployment.yaml, example/etcd-restore-operator/deployment.yaml, version/version.go
=> release: 0.8.1

version/version.go
=> version: bump to 0.8.1+git

hack/ci/run_e2e
=> hack: print images if skipped tests

test/logcollector/main.go
=> logcollector: print init container logs as well

CHANGELOG.md, example/deployment.yaml, example/etcd-backup-operator/deployment.yaml, example/etcd-restore-operator/deployment.yaml, version/version.go
=> release: 0.8.2

version/version.go
=> version: bump to 0.8.2+git

doc/user/spec_examples.md
=> doc: add etcd configuration example

pkg/util/k8sutil/k8sutil.go
fix https://github.com/coreos/etcd-operator/issues/1881
=> k8sutil: extend rand suffix length to 10

MAINTAINERS
=> MAINTAINERS: add rjtsdl for abs backup feature

README.md, doc/user/walkthrough/restore-operator.md
=> *: update doc on etcd pod suffix change

pkg/util/k8sutil/k8sutil.go
=> pkg/util: use randomized suffix

doc/user/backup_cronjob/README.md, doc/user/backup_cronjob/configmap.yaml, doc/user/backup_cronjob/cronjob.yaml, doc/user/walkthrough/backup-operator.md
[skip ci]
fix https://github.com/coreos/etcd-operator/issues/1832
=> doc: backup cronjob example

pkg/controller/backup-operator/sync.go
=> pkg/controller: fix typo

CHANGELOG.md
=> changelog: update changes

CHANGELOG.md, example/deployment.yaml, example/etcd-backup-operator/deployment.yaml, example/etcd-restore-operator/deployment.yaml, version/version.go
bump etcd operator version to 0.8.4
=> release: bump version to 0.8.4

version/version.go
=> version: bump version to 0.9.0+git

README.md
[skip CI]
follow up fix to #1920
=> README: fix delete pod

CHANGELOG.md, example/deployment.yaml, example/etcd-backup-operator/deployment.yaml, example/etcd-restore-operator/deployment.yaml, version/version.go
=> *: bump version to v0.9.1 and update changelog

version/version.go
[skip ci]
/cc @hongchaodeng @fanminshi
=> version: bump version to 0.9.1+git

doc/user/install_guide.md
[skip ci]
Signed-off-by: Hui Kang <kangh@us.ibm.com>
=> Delete crd on uninstallation of etcd-operator

CHANGELOG.md, example/deployment.yaml, example/etcd-backup-operator/deployment.yaml, example/etcd-restore-operator/deployment.yaml, version/version.go
=> release: bump version to v0.9.2 and update changelog

version/version.go
=> version: bump version to 0.9.2+git

cmd/restore-operator/doc.go
their is probably better than his/her
=> Small grammar fix

pkg/util/k8sutil/k8sutil.go
=> util: set a default DNSTimeout when pod policy is not specified

CHANGELOG.md
=> CHANGELOG: add DNSTimeoutInSecond 

doc/user/abs_backup.md
Closes #1987
/cc @fanminshi @mwieczorek
=> Add documentation for ABS backup

CHANGELOG.md, Gopkg.lock, Gopkg.toml
We are going to cut a new release based in 3.2.13 then bump etcd to 3.3.10 later.
=> *: revert etcd from 3.3.10 to 3.2.13

CHANGELOG.md, example/deployment.yaml, example/etcd-backup-operator/deployment.yaml, example/etcd-restore-operator/deployment.yaml, version/version.go
=> release: bump version to v0.9.3 and update changelog

version/version.go
=> version: bump version to 0.9.3+git

doc/user/clusterwide.md
=> doc: Fix Install Guide URL

.github/PULL_REQUEST_TEMPLATE.md
Adding basic PR contribution template.
[skip ci]
=> github: add pull request template

example/deployment.yaml
=> correct doc link in example deployment

CHANGELOG.md, doc/design/restore_operator.md, doc/user/upgrade/upgrade_guide.md, example/rbac/create_role.sh, pkg/util/k8sutil/k8sutil.go
This PR fixes the misspell words
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>
=> misspell:Fix misspell words

CHANGELOG.md, example/deployment.yaml, example/deployment_psp.yaml, example/etcd-backup-operator/deployment.yaml, example/etcd-restore-operator/deployment.yaml, version/version.go
[skip ci]
Signed-off-by: Sam Batschelet <sbatsche@redhat.com>
=> release: bump version to v0.9.4 and update changelog

CHANGELOG.md, version/version.go
=> version: bump version to 0.9.4+git
