coreos/etcd-operator

pkg/cluster/cluster.go
pkg/util/k8sutil/backup.go

Currently we encountered a race in replicaset (TODO: issue number).
Instead, we will only delete etcd pods and let replica set delete the backup pod.

Fix orphan backup pod

---

pkg/cluster/cluster.go
pkg/spec/backup.go
test/e2e/e2e_test.go

First of all, it's already in Backup. We don't need to say "cleanup backup" again.
Second, we make the event more explicit than "IfDeleted".

spec/backup: rename CleanupBackupIfDeleted -> CleanupOnClusterDelete

---

pkg/cluster/reconcile.go

cluster: use correct error type for member not found

---

hack/build/operator/Dockerfile
hack/build/operator/build
hack/jenkins
hack/release/README.md

Fix #361
We are using "alpine" as base images now. The output is just 27MB on quay, compared to ~400MB previously.
docker images:
```
quay.io/coreos/etcd-operator                           test                          9773f55873c3        10 minutes ago      137.3 MB
```
Compared to 1.2GB previously.
Not sure why they are different though.

build: shrink docker image size

---

hack/test

Recently We have seen many test timeout error:
```
Test killed: ran too long (10m0s)
```
One change I made is that I have downgraded k8s master from n4 to n2. After that test started failing.

e2e_test: increase timeout to 30m

---

hack/build/operator/Dockerfile

alpine doesn’t have CA certificates. We need to add them so that AWS
client could be created securely.

Dockerfile: add ca-certificates in alpine image

---

hack/jenkins
test/e2e/framework/framework.go
test/e2e/restore_test.go
test/e2e/util.go

We have changed the jenkins setup to create namespace outside.
We don't need to create ns again.
It also doesn't make sense to get the ns object from k8s again.
The 'Namespace' field in framework should be changed to string too
so that we can just use given param directly.

e2e: framework use ns string param directly

---

pkg/cluster/backup_manager.go
pkg/cluster/backupstorage/pv.go
pkg/cluster/backupstorage/s3.go
pkg/cluster/backupstorage/storage.go
pkg/cluster/cluster.go

Previously, on controller restore case, backup manager “storage” field will be nil due to not calling setup in “isNewCluster” logic block.
Instead, we always construct “storage” field in newBackupManager(). We also introduce a new logic called “hasExist” to indicate whether we have existing storage created, e.g. not new cluster case, restoring same cluster name case.

backup_manager: construct storage on controller restore

---

pkg/cluster/backup_manager.go
pkg/cluster/cluster.go
pkg/cluster/reconcile.go
pkg/cluster/self_hosted.go
pkg/cluster/upgrade.go
pkg/controller/controller.go

In details, we will need both TypeMeta and ObjectMeta of EtcdCluster to set OwnerRef.
Conceptually, the cluster should have a EtcdCluster obj as its knowledge. The entire object provides more than Spec.

cluster: pass in EtcdCluster object

---

pkg/cluster/cluster.go

Recently we have test failure in https://jenkins-etcd.prod.coreos.systems/job/etcd-operator/981/console,
It has messages like:
```
failed to update TPR status: unexpected status: 409 Conflict
…
```
However, there are two places that have the same message. We need to differentiate them.

cluster: make logging unique

---

pkg/cluster/cluster.go
pkg/util/k8sutil/tpr_util.go

If updateTPRObject() failed with conflict, delete will keep looping because the version doesn’t get updated.

cluster: get latest if update status fail

---

pkg/cluster/backup_manager.go
pkg/cluster/backupstorage/pv.go
pkg/cluster/backupstorage/s3.go
pkg/cluster/backupstorage/storage.go
pkg/cluster/cluster.go
pkg/controller/controller.go
pkg/spec/cluster.go

Previously, controller list TPR could potentially restore a cluster
that was created fresh.
Previously, we also didn’t do failed status reporting on failure to new
and didn’t set running status immediately.
https://github.com/coreos/etcd-operator/pull/553#issuecomment-269705792

cluster: use status phase to detect new cluster

---

pkg/cluster/cluster.go
pkg/cluster/member.go
pkg/cluster/reconcile.go
pkg/cluster/self_hosted.go

ref: https://github.com/coreos/etcd-operator/issues/532#issuecomment-269559591
Because the membership knowledge will be outdated if any error happened in reconcile(), we need to list member again on such cases.
Another thing is that previously we make assumptions on “c.members = nil” on certain cases, e.g. seed member, member not ready. We are trying to get rid of them.

cluster: update members before reconcile if needed

---

pkg/cluster/reconcile.go
pkg/util/etcdutil/member.go
pkg/util/etcdutil/member_test.go

Previously, we didn’t check running size and spec size. This is not
enough — we didn’t take into account cluster membership.
Now the condition would be, if running set isn’t exactly the same as
cluster membership, or if member size isn’t the same as spec size, we
would need to call reconcileMembers (previously reconcileSize). That’s
basically what the function does.

cluster: reconcile members condition check

---

pkg/cluster/cluster.go
pkg/cluster/error.go
pkg/cluster/reconcile.go
pkg/spec/cluster.go

Centralize error handling:
- disaster recovery
- update members
- reconcile
We'd better do further refactoring work to combine these into reconcile(). But I have other changes on top to carry right now. Will do it later.

cluster: refactor error handling in run

---

pkg/cluster/cluster.go
pkg/cluster/error.go
pkg/cluster/member.go
pkg/cluster/self_hosted.go
pkg/util/etcdutil/etcdutil.go
pkg/util/etcdutil/etcdutil_test.go

Problem statement: We could fail in MemberAdd() due to context deadline
exceeded and thus not creating related pod/service. But we could have
added the member. Then we would end up infinitely looping on updateMembers()
on "not ready member" error.
One idea is that we can get name from member's PeerURL.
For self hosted case, it's more complicated because it's host IP.
We currently loop wait until the member has been added successfully.
In the future we could use pod IP to match.

cluster: get name from PeerURL if member unready

---

pkg/controller/controller.go

We forget to set default version in finding existing clusters

controller: should always set default version

---

test/e2e/util.go

Error message didn’t tell us what pod it is. We can’t query the log from cloud.
```
failed: Get http://10.36.0.228:19999/backupnow: EOF
```

e2e: add pod name info on err msg

---

pkg/cluster/cluster.go

Our etcd pod has 5s delay on bootstrap. So current reconcile interval
(5s) will fail immediately after adding one member before another.
Increasing the interval to avoid that.

cluster: set reconcile interval to 8s

---

pkg/cluster/cluster.go
pkg/controller/controller.go
pkg/spec/cluster.go

1. do not recover any failed cluster
2. always recover status from the existing etcd cluster TPR item if possible
3. make status the source of truth after the cluster struct is materialized

*: simplify status recovery logic

---

test/e2e/recovery_test.go

Print out what we have deleted. Helps debug https://github.com/coreos/etcd-operator/issues/627

e2e: print out pods to delete

---

pkg/controller/controller.go

We should pass in copied EtcdCluster obj instead of passing “item”. item is from the for loop and could be changed if running concurrently.
Also make naming better by changing all event.Object, item into clusterObj.

controller: pass copied cluster obj and refactor

---

pkg/cluster/backupstorage/s3.go
pkg/controller/controller.go
pkg/controller/s3.go

On operator side, some clusters’ S3 backup manager will talk to AWS/S3
and manage storage. However, previously we will setup the credentials/config
for each cluster and they share the same path. This will cause
concurrency issue.
Instead, we should initialize AWS config/creds only once at controller
startup. It will be shared and used by potential cluster's S3 backup
manager to manage storage on operator side.

AWS: config/creds setup should init only once

---

pkg/cluster/cluster.go
pkg/controller/controller.go

We have New() blocking because we need to handle the error previously.
Now we will report failed status if error happens.
Meanwhile, cluster shouldn’t block or interfere each, which we have
seen in some issues. This is gonna fix #607, #588.

cluster: New() made async

---

hack/jenkins
hack/release/README.md

Reverts coreos/etcd-operator#646
The build becomes flaky today. I tried that reverting this will make build stable again. Let's not break the master first.
As mentioned in https://github.com/coreos/etcd-operator/issues/649, it's still broken.

Revert "*: add glide install options"

---

pkg/cluster/cluster.go
pkg/cluster/reconcile.go

Previously, we reset "members = nil" on creating seed member (including
disaster recovery case) and use this state to decide to call
updateMembers(). Now if seed member is created successfully,
we just set membership and optimize one round of member listing.

cluster: set members if seed member created successfully

---

cmd/operator/main.go
glide.lock
glide.yaml
hack/jenkins
hack/release/README.md
pkg/backup/backup.go
pkg/chaos/chaos.go
pkg/cluster/backup_manager.go
pkg/cluster/backupstorage/pv.go
pkg/cluster/backupstorage/s3.go
pkg/cluster/cluster.go
pkg/cluster/member.go
pkg/cluster/reconcile.go
pkg/cluster/self_hosted.go
pkg/cluster/upgrade.go
pkg/controller/controller.go
pkg/controller/s3.go
pkg/garbagecollection/gc.go
pkg/spec/cluster.go
pkg/spec/etcd_cluster_list.go
pkg/util/k8sutil/backup.go
pkg/util/k8sutil/k8sutil.go
pkg/util/k8sutil/pod_util.go
pkg/util/k8sutil/self_hosted.go
pkg/util/k8sutil/tpr_util.go
test/e2e/basic_test.go
test/e2e/framework/framework.go
test/e2e/restore_test.go
test/e2e/self_hosted_test.go
test/e2e/util.go

This PR includes:
- vendoring change
- k8s client migration change towards client-go/1.5
Most of the client has been changed except leader election package. Expect maybe 2 more weeks before upstream import that.
I have the PR also tested on jenkins for a couple of rounds. All green.

migrate to client-go/1.5

---

cmd/operator/main.go
glide.lock
glide.yaml
pkg/util/k8sutil/election/README
pkg/util/k8sutil/election/election.go
pkg/util/k8sutil/election/resourcelock/endpointslock.go
pkg/util/k8sutil/election/resourcelock/interface.go

client-go doesn’t have leader election package imported at the moment. We are trying our best to communicate with upstream and get that package imported to client-go.
Meanwhile, that process is slow, and even complicated due to a few aspects:
- The importing work seems to be happening on 2.0/master but not 1.5 that we are using.
- We are using client-go 1.5 which is k8s 1.4, and we need to pull packages from k8s 1.5 due to some concern. This is mixing versions, which gets things more complicated.
- This might introduce new API to client-go 1.5, which might get things more complicated.
- There are still concerns on upstream on “write to endpoints”. This is the most complicated.
The situation is complicated, and we need to expedite our work.
This PR is to pull the changes into operator …

import leader election here and remove k8s dep

---

test/e2e/self_hosted_test.go

Seeing “bind: address already in use” which cause the entire test suite
to fail. This is annoying. Improving the situation.

e2e: make boot member port random

---

pkg/cluster/backup_manager.go
pkg/util/k8sutil/backup.go
pkg/util/k8sutil/k8sutil.go

Since it’s owned by the cluster TPR, backup service should be list-able
in GC.
Backup pods doesn’t need to because replica set manages it.
Also do some refactoring, renaming stuff.

k8sutil: make backup service labels same as ClusterListOpt()

---

pkg/backup/s3/s3.go
pkg/backup/s3_backend_test.go
pkg/cluster/backupstorage/s3.go

Trying to contain the prefix logic in the package itself.
This would help https://github.com/coreos/etcd-operator/pull/689

s3: refactor prefix code

---

test/e2e/self_hosted_test.go

ref: https://github.com/coreos/etcd-operator/issues/693
This would make it not blocking and have better error message

e2e: don't block forever on etcd server ReadyNotify()

---

doc/user/backup_service.md
pkg/backup/backup_test.go
pkg/backup/http.go
pkg/backup/version.go

For GET /backup requests, set EtcdVersion and Revision in headers.

backup: add metadata to GET response header

---

pkg/cluster/reconcile.go

It’s “addr//v1” right now. Not sure how it works. But it should be
fixed.

cluster: fix double "/"

---

hack/build/operator/build

fix https://github.com/coreos/etcd-operator/issues/704

build: speed up using "go install"

---

pkg/cluster/cluster.go
pkg/garbagecollection/gc.go

Give time to etcd to react on SIGTERM. This allows leader transfer to
happen before etcd gets SIGKILLed.
Fix https://github.com/coreos/etcd-operator/issues/677

cluster: remove pod with grace period

---

pkg/cluster/cluster.go

After second thought, I believe we should simply block the
operator if one of the cluster cannot make progress.
It is either caused by a bug in client-go (unlimited request waiting)
or in our code (forget to set timeout?). If that happens, the best solution
(or simplest solution) would be restarted the operator. That should be
handled at the controller layer.
So in short, we should just let it blocking when it blocks.
Fix https://github.com/coreos/etcd-operator/issues/624

cluster: remove panic

---

pkg/controller/controller.go
pkg/controller/util.go

If this patch works, then operator will not restart when there is not external issues.
Fix https://github.com/coreos/etcd-operator/issues/652.

controller: best effort recovery on watch failure

---

test/e2e/self_hosted_test.go

Over the past few days, I have observed that self hosted tests failed
due to two tests run at same time, e.g. PR and master, flaketest and
PR. When this happened, it requires 6 nodes for each test and
concurrent tests will exceed our current node size.
Disable it now. Once we have larger jenkins cluster, we can enable it.

e2e: disable parallel of self hosted test

---

pkg/cluster/cluster.go
pkg/garbagecollection/gc.go

fix https://github.com/coreos/etcd-operator/issues/732
First of all, we should ignore not found error, this could happen if
the full GC also takes place.
Second, on encountering error, we should log the error, but don’t stop
and continue to gc other objects.

gc: ignore not found, and not stop on one error

---

README.md
client/experimental/client.go
doc/design/cluster_restore.md
doc/design/s3_backup.md
example/example-etcd-cluster-with-backup.yaml
example/example-etcd-cluster.yaml
pkg/controller/controller.go
pkg/spec/cluster.go
pkg/util/k8sutil/tpr_util.go
test/e2e/util.go

Change group to “etcd.coreos.com”; change version to “v1beta1”.
We made this change because it’s impossible to have multiple versions
in one group

TPR: change group and version

---

client/experimentalclient/client.go
pkg/cluster/backup_manager.go
pkg/cluster/cluster.go
pkg/controller/controller.go
pkg/controller/util.go
pkg/spec/cluster.go
pkg/spec/etcd_cluster_list.go
pkg/util/k8sutil/tpr_util.go
test/e2e/util.go

So does EtcdClusterList -> ClusterList
Otherwise, tpr client will complain kind unrecognized "EtcdCLuster".
It seems like it's using Go's reflect.

spec: change EtcdCluster to Cluster

---

client/experimentalclient/client.go
pkg/cluster/backup_manager.go
pkg/cluster/cluster.go
pkg/cluster/reconcile.go
pkg/cluster/self_hosted.go
pkg/cluster/upgrade.go
pkg/controller/controller.go
pkg/garbagecollection/gc.go
pkg/spec/cluster.go
pkg/spec/etcd_cluster_list.go
pkg/util/k8sutil/tpr_util.go
test/e2e/basic_test.go
test/e2e/recovery_test.go
test/e2e/resize_test.go
test/e2e/restore_test.go
test/e2e/self_hosted_test.go
test/e2e/util.go

There is known issue with TPR in client-go:
https://github.com/kubernetes/client-go/issues/8
Workarounds:
- We include `Metadata` field in object explicitly.
- Copy the solutions from client-go TPR examples to work around a
known problem with third-party resources and ugorji.
```go
type ClusterListCopy ClusterList
type ClusterCopy Cluster
func (c *Cluster) UnmarshalJSON(data []byte) error {
tmp := ClusterCopy{}
err := json.Unmarshal(data, &tmp)
if err != nil {
return err
}
tmp2 := Cluster(tmp)
*c = tmp2
return nil
}
func (cl *ClusterList) UnmarshalJSON(data []byte) error {
tmp := ClusterListCopy{}
err := json.Unmarshal(data, &tmp)
if err != nil {
return err
}
tmp2 := ClusterList(tmp)
*cl = tmp2
return nil
}
```

*: fix tpr client

---

pkg/controller/controller.go
pkg/controller/util.go

Panic the controller when it blocks on one operation for too long.
The operation should be non-blocking. Kubernetes should be able to
restart the operator when it panics.
This is just a defensive approach.

controller: add panicTimer

---

client/experimentalclient/client.go
pkg/spec/cluster.go

Fix client code as a pre-step to client e2e test:
- pass in kind plural instead of tpr name to Resource().
I have verify it work in e2e. Want to separate them in PRs.

*: fix client

---

pkg/cluster/backup_manager.go
pkg/cluster/cluster.go
pkg/spec/backup.go
pkg/spec/cluster.go

We should have separate backupapi/ and spec/ ’s BackupServiceStatus.

*: add spec BackupServiceStatus

---

test/e2e/recovery_test.go
test/e2e/util.go

point 4 in issue: https://github.com/coreos/etcd-operator/issues/788
Just sleep a little bit instead of relying on pod IP.

e2e: remove check member ready

---

hack/test

hack/test: add codecov reporting script
Calls the script to send the coverage reports to codecov everytime the unit tests are run.
Previously part of the jenkins bash script.
fix #719 

hack/test: call codecov bash script from inside unittest

---

codecov.yaml

The [codecov.yaml](https://docs.codecov.io/docs/codecov-yaml) file is used to change the default behavior of the codecov repo.
After this merge the codecov pr comment will be disabled. Will still be generated for this pr.

codecov.yaml: turn off pr coverage reports

---

CHANGELOG.md
pkg/backup/backend.go
pkg/backup/backup.go
pkg/backup/backupapi/types.go
pkg/backup/file.go
pkg/backup/http.go
pkg/backup/s3.go
pkg/backup/s3/s3.go
pkg/backup/util.go
pkg/spec/backup.go

Also change size from int64 to float64. It is not a breaking change since JSON does not differentiate about int and float (actually number is double type in JSON).

*: add total size into backup status

---

CHANGELOG.md
pkg/spec/cluster.go
pkg/util/k8sutil/k8sutil.go
pkg/util/k8sutil/self_hosted.go

Make it more consistent with k8s naming. PromO also uses this naming.

spec: PodPolicy `resourceRequirements` field is renamed to `resources`

---

test/e2e/cluster_status_test.go
test/e2e/framework/framework.go
test/e2e/restore_test.go
test/e2e/self_hosted_test.go

Added an environment variable to skip 3 tests(ClusterRestore,SelfHosted and BackupStatus) that fail consistently on an AWS cluster. This is for ease of debugging on AWS.

test/e2e: add env to skip tests

---

test/e2e/recovery_test.go

These two tests are relying on pod IP reachability.
Will fix them later.

e2e: skip test on aws

---

client/cliente2e/test
hack/test

That's jenkins specific variable.
We should use KUBECONFIG instead.

test: get rid of KUBERNETES_KUBECONFIG_PATH

---

hack/test

We put k8s under `_test/` .
[skip ci]

test_check: ignore _test

---

README.md
doc/user/spec_examples.md
example/example-etcd-cluster-with-backup.yaml
example/example-etcd-cluster.yaml
pkg/spec/cluster.go
test/e2e/basic_test.go

A raft issue is fixed in 3.1.2 . Should recommend users to use it.

*: update default etcd version to 3.1.2

---

doc/user/rbac.md
hack/ci/create_rbac_role
hack/ci/rbac_utils.sh
hack/test

Create a ClusterRole and ClusterRoleBinding if k8s supports rbac.
Also change the rbac documentation for the correct verb to use for permissions to the configmap and secrets.
#840 

ci: create role and binding if rbac present

---

cmd/operator/main.go
pkg/util/k8sutil/k8sutil.go

close https://github.com/coreos/etcd-operator/issues/731
I have tested the DNS lookup code and it works.

k8sutil: work around kubelet race not setting correct pod env

---

test/e2e/basic_test.go
test/e2e/framework/framework.go

The current sleep 2s is a wrong assumption. Even if we set GP to 1s, it might still take >1s to make the pod gone from API.

e2e: check etcd operator gone from API

---

hack/ci/run
hack/test

Additional flag to selectively filter e2e tests for ease of testing on jenkins. The default behavior to run all e2e tests remains the same.

ci: add test selector flag in jenkins script

---

README.md

Change the build badge link to point to the new jenkins job which tests against upstream k8s master.
[skip ci]

README: change link for build badge

---

pkg/spec/cluster.go

Outline for keeping track of number of healthy pods etcd cluster.
My first thought are just to send HTTP GET requests to each running pod after the cluster is reconciled.
Is this the right place to do this?

spec/ClusterStatus: track healthy pods

---

pkg/cluster/cluster.go
pkg/util/etcdutil/etcdutil.go

Change health probe to linearizable to test out tracking of ReadyMembers.
Do not merge yet.
#808

cluster: change probe to linearizable

---

CHANGELOG.md
pkg/cluster/cluster.go
pkg/spec/cluster.go
test/e2e/cluster_status_test.go

Added another struct MembersStatus to group the ready and unready members together.
Fixes #878 

spec/ClusterStatus: group ReadyMembers and UnreadyMembers together

---

pkg/util/etcdutil/etcdutil.go

fix https://github.com/coreos/etcd-operator/issues/890
depends on https://github.com/coreos/etcd-operator/pull/889

cluster: check healthy via serializable get()

---

CHANGELOG.md
pkg/cluster/cluster.go

Verified it fixed https://github.com/coreos/etcd-operator/issues/900
Previously we were skipping reconcile if there are unready members.
However, this is unpredictable — member could be transition from ready
back to unready. Our initial reason for skipping is actually for
pending state, a stage that we think a pod would be running later
because of slow image pulling. We should only skip reconcile if pods
are pending. This is more deterministic.
Moved update members status right before update TPR status. This is not
gonna show pending pods as unready and might be slower to show ready
members.

cluster: fix looping of reconcile skip due to unready members

---

pkg/util/k8sutil/k8sutil.go

Externally, ready/unready member slice relies on this.
We want it to be nil to be consistent.
But if pods parameter is nil, it also makes more sense to return nil.

k8sutil: GetPodNames() return nil if slice is empty

---

CHANGELOG.md
pkg/backup/backup.go
pkg/backup/backupapi/types.go
pkg/spec/backup.go
pkg/spec/cluster.go

fix https://github.com/coreos/etcd-operator/issues/910
There is a problem when using DeepEqual() to compare ClusterStatus
structs — time.Time isn’t comparable. We change it to string. This is
backward compatible and should be no effect on upgrade

spec: change time type to string

---

CHANGELOG.md
cmd/operator/main.go
pkg/cluster/backup_manager.go
pkg/cluster/backup_manager_test.go
pkg/controller/controller.go
pkg/util/constants/constants.go

If “pv-provisioner” is set to “none”, then operator won’t create any
storage class and users couldn’t make use of PV backup feature.
Also fix that if s3 config isn’t set but spec asks for “S3” storage
type, we will reject it immediately.
fix https://github.com/coreos/etcd-operator/issues/921

backup: add "none" storage type

---

pkg/controller/controller.go
pkg/controller/controller_test.go
test/e2e/cluster_status_test.go

If cluster was failed, it would show in cluster status. User would then
delete it. But there are two problems: 1. we didn’t cleanup resources;
2. we have a logging which is confusing — “ignore failed cluster …”

controller: fix logic for deleting failed cluster

---

README.md
doc/user/backup_config.md
example/deployment-s3-backup.yaml.template

[skip ci]
Some further clarifications and a broken link fix in the docs explaining how to enable S3 backups.
Added `example/deployment-s3-backup.yaml.template` to show the flags that need to be passed to the operator pod.

docs: more explanations for enabling S3 backups

---

pkg/cluster/cluster.go
pkg/util/etcdutil/member.go
pkg/util/k8sutil/k8sutil.go

With cluster name as subdomain grouping, we can do TLS
SAN wildcard more accurately.
/cc @colhom @hongchaodeng

*: use pod A record as fqdn for better grouping

---

doc/user/op_guide.md

We need to highlight the rbac setup part just before creating the operator since it's easy to skim past the RBAC docs link in the overview.
A few users have already faced this problem and with rbac being default in k8s 1.6 this will become more common.
[skip ci]

op_guide: highlight rbac setup

---

doc/user/cluster_tls.md
pkg/spec/cluster_tls.go
pkg/util/etcdutil/etcdutil.go
test/e2e/tls_test.go

Update the user docs to reflect operator's client key/cert and
etcd server's client key/cert.
Meanwhile, change the staticTLS fields to be pointer so that we preserve
the possibility of more options.

TLS: update docs (client communication)

---

hack/ci/rbac_utils.sh

Test infra needs this for concurrent runs.
What's more, making this namespace specific is more manageable.

rbac_util: make rbac setup/cleanup namespace specific

---

test/e2e/recovery_test.go

The last pod could have not come up yet.
A simple solution is to kill the last pod.
fix https://github.com/coreos/etcd-operator/issues/975

e2e: kill the last pod in recovery test

---

pkg/spec/cluster.go

We are doing a new release. Unfortunately TLS isn’t fully implemented yet. TLS feature will be put off onto next release.
This PR is to ignore the TLS field to make it no effect.

spec: ignore TLS field

---

hack/ci/run
hack/test
pkg/backup/s3/s3.go
pkg/cluster/cluster.go
pkg/util/k8sutil/k8sutil.go
test/e2e/framework/framework.go

Added checks for `unused` and `gosimple`.
Fixes #876 
Also corrected changes pointed out by the above checks:
```
Checking unused...
unused checking failed:
pkg/cluster/cluster.go:85:2: field backupDir is unused (U1000)
pkg/cluster/cluster.go:390:19: func (*Cluster).deleteClientServiceLB is unused (U1000)
pkg/util/k8sutil/k8sutil.go:51:2: const annotationPrometheusScrape is unused (U1000)
pkg/util/k8sutil/k8sutil.go:52:2: const annotationPrometheusPort is unused (U1000)
Checking gosimple...
gosimple checking failed:
pkg/backup/s3/s3.go:73:2: 'if err != nil { return err }; return nil' can be simplified to 'return err' (S1013)
pkg/backup/s3/s3.go:98:2: 'if err != nil { return err }; return nil' can be simplified to 'return err' (S1013)
pkg/cluster/cluster.go:417:2: 'if err != nil { return …
```

hack/test: add unused and gosimple checks

---

test/e2e/upgradetest/upgrade_test.go

Done the basic workflow of an upgrade test:
- create operator
- create cluster
- upgrade operator
- resize the cluster works
The code isn’t modular yet but we will improve it in next PR.
Gonna add a script and set up a job to run upgrade test too.

upgradetest: add resize test

---

hack/test
test/e2e/upgradetest/README.md

I have set up a **NIGHTLY** jenkins job: https://jenkins-etcd.prod.coreos.systems/view/operator/job/etcd-operator-upgrade/
It will do upgrade test trying to upgrade from latest release to tip version of etcd operator.

	hack/test: add upgrade test

---

pkg/util/k8sutil/tpr_util.go
test/e2e/basic_test.go
test/e2e/resize_test.go
test/e2e/util.go

Unconditional update will overwrite TPR and we should not use it.

e2e: safe update TPR instead of unconditional update

---

test/e2e/upgradetest/upgrade_test.go

This is broken by https://github.com/coreos/etcd-operator/pull/1023

upgradetest: fix compile

---

pkg/util/k8sutil/tpr_util.go
test/e2e/basic_test.go
test/e2e/e2eutil/tpr_util.go
test/e2e/resize_test.go
test/e2e/upgradetest/upgrade_test.go
test/e2e/util.go

`AtomicUpdateClusterTPR` avoids overwriting the cluster TPR by fetching the latest cluster TPR and applying an update function to modify it before attempting to update the cluster TPR object.
This could fail if our fetched TPR becomes outdated before we can modify and update it. 
So the whole process is retried with exponential backoff for `Step` number of times until the update is successful, else we return an error.
Also changed is `updateEtcdCluster` in `e2e/util.go` which now accepts an update function in order to use `AtomicUpdateClusterTPR`.
@hongchaodeng I have not modified upgrade_test.go to use `AtomicUpdateClusterTPR` though it should be a similar change once it starts using `e2e/util.go`

tpr_util,e2e/util: AtomicUpdateClusterTPR to retry safe update

---

test/e2e/basic_test.go
test/e2e/cluster_status_test.go
test/e2e/e2eutil/tpr_util.go
test/e2e/recovery_test.go
test/e2e/resize_test.go
test/e2e/restore_test.go
test/e2e/self_hosted_test.go
test/e2e/tls_test.go
test/e2e/upgradetest/upgrade_test.go
test/e2e/util.go

Refactored the `CreateCluster()` function and moved it to `e2eutil/tpr_util.go` since it's a common function.
upgrade_test.go is also changed to use the `CreateCluster()` func.

e2e/util.go: refactor CreateCluster() into e2e/e2eutil for common use

---

CHANGELOG.md
doc/user/rbac.md
hack/ci/rbac_utils.sh
pkg/cluster/backup_manager.go
pkg/cluster/cluster.go
pkg/garbagecollection/gc.go
pkg/util/k8sutil/backup.go
pkg/util/k8sutil/k8sutil.go
test/e2e/upgradetest/framework/framework.go
test/e2e/util.go

ref https://github.com/coreos/etcd-operator/issues/1014
This PR changes backup sidecar to use Deployment, and upgrade backup sidecar automatically if operator is upgraded.
It also handles backward compatibility:
```
Once operator is upgraded, all backup-enabled cluster will go through
an upgrade process that deletes backup sidecar's ReplicaSet and creates
new Deployment for sidecar. If upgrading failed for any reason, cluster
TPR's `status.phase` will be FAILED. Recreate of the cluster TPR is
needed on failure case.
```
I have manually test upgrade. We need upgrade test for it later before next release.

backup: use Deployment to manage sidecar instead od ReplicaSet

---

test/e2e/basic_test.go
test/e2e/cluster_status_test.go
test/e2e/e2eutil/tpr_util.go
test/e2e/e2eutil/util.go
test/e2e/recovery_test.go
test/e2e/resize_test.go
test/e2e/restore_test.go
test/e2e/self_hosted_test.go
test/e2e/tls_test.go
test/e2e/upgradetest/upgrade_test.go
test/e2e/util.go

Moved `DeleteEtcdCluster()` into `e2eutil/tpr_util.go` and made it more generic by not passing the framework.
The helper functions for `DeleteEtcdCluster()`,  `waitResourcesDeleted()` and `waitBackupDeleted()` have been moved to `e2eutil/util.go`.
In order to make `waitBackupDeleted()` support checking of different types of storage options in the future, a new wrapper struct `StorageCheckerOptions` is passed to `DeleteEtcdCluster()` which is then type asserted to the correct type of storage option.

e2e/util.go: refactor DeleteCluster() for common use between different frameworks

---

test/e2e/basic_test.go
test/e2e/cluster_status_test.go
test/e2e/e2eutil/spec_util.go
test/e2e/e2eutil/tpr_util.go
test/e2e/recovery_test.go
test/e2e/resize_test.go
test/e2e/restore_test.go
test/e2e/self_hosted_test.go
test/e2e/tls_test.go
test/e2e/upgradetest/upgrade_test.go
test/e2e/util.go

Cluster spec methods grouped in `e2eutil` but mostly unchanged.

e2e/util.go: Move etcd spec related methods into e2eutil for common use

---

test/e2e/basic_test.go
test/e2e/cluster_status_test.go
test/e2e/e2eutil/tpr_util.go
test/e2e/e2eutil/util.go
test/e2e/e2eutil/wait_util.go
test/e2e/recovery_test.go
test/e2e/resize_test.go
test/e2e/restore_test.go
test/e2e/self_hosted_test.go
test/e2e/tls_test.go
test/e2e/upgradetest/upgrade_test.go
test/e2e/util.go

Moved `waitUntilSizeReached` functions with the other `waitUntilSomething` functions in `e2eutil/wait_util.go`.
Other common functions like `LogfWithTimestamp` have been moved to `e2eutil/util.go`

e2e/util.go: Move waitUntilSize functions to e2eutil for common use

---

client/cliente2e/client_test.go
test/e2e/framework/framework.go
test/e2e/upgradetest/framework/framework.go

We might not use versioned image in test, e.g. nightly build dev image.

e2e: test should always pull latest image

---

test/e2e/upgradetest/upgrade_test.go

Check for the creation of the TPR, after creating operator deployment, by polling for the presence of the API path:
`/apis/etcd.coreos.com/v1beta1/namespaces/<namespace>/clusters/`
No need to wait after deleting the cluster since `DeleteCluster()` already does `waitResourcesDeleted()` and `waitBackupDeleted()`.
Also no need to wait after updating the operator deployment since we do `WaitUntilSizeReached()` after changing cluster size.

upgradetest/TestResize: wait for cluster TPR, remove unnecessary waits

---

doc/user/client_service.md

[skip ci]
Added documentation on how to access the client service from a pod within the cluster (similar to the README), and how to create a load balancer service to access the client API from outside the cluster.
I have not mentioned how to use an existing load balancer though I assume that should be simple enough by just setting the IP field.
fixes #1016 

doc: access the client service using lb

---

test/e2e/e2eutil/util.go
test/e2e/upgradetest/framework/framework.go
test/e2e/upgradetest/upgrade_test.go

- Added an `e2e/upgrade` test for the newer operator to successfully heal the cluster back to size after a single member failure.
- Moved `KillMembers()` from `e2e/util.go` to `e2e/e2eutil/util.go` to make it common between `e2e` and `e2e/upgradetest` tests.
- Changed the deployment delete grace period to zero, and wait for deployment pods to be deleted, so that the deployment from the previous test is gone before it conflicts with the next test's creation.

e2e/upgradetest: 1 member recovery test

---

pkg/util/retryutil/retry_util.go
test/e2e/e2eutil/wait_util.go
test/e2e/upgradetest/framework/framework.go

We will also need to use this util in upgrade test for:
- wait old version etcd operator deleted
- wait old version backup sidecar deleted

e2eutil: add WaitPodsDeleted util families

---

hack/test
test/e2e/e2eutil/etcd_util.go
test/e2e/e2eutil/wait_util.go
test/e2e/restore_test.go
test/e2e/tls_test.go
test/e2e/upgradetest/upgrade_test.go
test/e2e/util.go

- Added `TestRestoreFromBackup ` to test if the upgraded operator can restore a cluster from the backup of an older cluster.
- Moved utils for reading and writing data to the etcd cluster into `e2eutil/etcd_util.go`.
- Added a test selector in `upgrade_pass` to make it easy to selectively run tests. And a timeout of 30m since all upgrade tests take at least 10 minutes currently.
- Made the `genName` passed to `CreateCluster()` unique for each upgrade test for ease of manual testing.

upgradetest: Add test to restore from backup of old cluster

---

pkg/cluster/cluster.go
pkg/cluster/metrics.go

fix https://github.com/coreos/etcd-operator/issues/737.
we do not really have ALL the metrics we want. but adding metrics around reconcile is probably good enough to start with.

cluster: add basic metrics

---

test/e2e/upgradetest/upgrade_test.go

[skip ci]
No need to set the backup interval since our test is not reliant on the periodic backup.

upgradetest: remove backup interval

---

test/e2e/upgradetest/upgrade_test.go

[skip ci]
Only keep periodic backup interval long for `TestBackupForOldCluster` and not for `TestRestoreFromBackup` since it doesn't matter in that case if periodic backup is made or not.
Revert #1087

upgradetest: remove other backupinterval

---

pkg/backup/backup.go
pkg/cluster/backupstorage/s3.go

Removed `CopyPrefix(clusterName)` so the backup manager will no longer be backwards compatible with non-namespaced s3 backups created by operators <= v0.2.5

*: drop compatability for non-namespaced s3 backup paths

---

test/e2e/upgradetest/upgrade_test.go

This is new feature we introduced in 0.3.x .
Current upgrade test is starting against 0.2.x. Disable them for now.
We are going to enable it again after 0.3.x release.
[skip ci]

upgrade_test: disable per cluster S3 policy for 0.2.x

---

glide.lock
glide.yaml

Not much different but pin to a release version.

glide: aws-sdk-go v1.8.23

---

doc/user/backup_config.md
doc/user/spec_examples.md

[skip ci]
Updated the sections in backup_config.md `S3 on AWS` to explain how to setup operator and cluster level S3 backup configurations.
The link in `Cluster level configuration` to the section `S3 backup and cluster specific S3 configuration` will start working once the PR is merged and spec_examples.md is updated.

doc: update instructions for per cluster S3 backup configurations

---

test/e2e/upgradetest/upgrade_test.go

Since we have released 0.3.0, we should re-enable these tests
[skip ci]

upgrade_test: re-enable per cluster S3 tests

---

test/e2e/cluster_status_test.go
test/e2e/e2eutil/spec_util.go
test/e2e/recovery_test.go
test/e2e/restore_test.go
test/e2e/upgradetest/upgrade_test.go

There is a lot of `CleanupBackupsOnClusterDelete` scattered around. They can be simplified if we initiate them in NewXXBackupPolicy()

e2e: refactor NewXXBackupPolicy() to include cleanup option

---

doc/design/cluster_status.md
doc/design/cluster_tls.md
doc/user/backup_service.md

~[The cluster_tls page](https://coreos.com/operators/etcd/docs/latest/design/cluster_tls.html#trust-delegation-diagram) has a diagram which includes mixed spaces and tabs, making it look mangled. This fixes that malformatting.~
~cc @colhom  to make sure the diagram is correct.~
UDPATE: Actually we're deleting that doc instead. @hongchaodeng does this look good to you? I can remove that other commit.
[skip ci]

doc: correct diagrams; replace tabs with sapces.

---

CHANGELOG.md
pkg/backup/backup.go
test/e2e/self_hosted_test.go

Currently Backup Sidecar is not able to talk to etcd pods because
it is using the FQDN which isn't supported in self hosted yet.
For self-hosted case, we are going to use PodIP.
fix https://github.com/coreos/etcd-operator/issues/1107

selfHosted: fix backup unable to talk to etcd pods 

---

test/e2e/self_hosted_test.go

Seems like somehow we didn’t set AWS_TEST_ENABLED=true in master jenkins job..
Fixed in jenkins. Also adding the check here.

e2e: add missing AWS_TEST_ENABLED check

---

doc/user/upgrade/incompatible_upgrade.md
doc/user/upgrade/upgrade_guide.md

The downstream documentation on coreos.com does not like absolute URLs.
This is the upstream patch to remove those absolute paths.

remove aboslute path references in docs.

---

pkg/cluster/backup_manager.go
pkg/cluster/cluster.go
pkg/garbagecollection/gc.go
pkg/util/k8sutil/k8sutil.go
test/e2e/e2eutil/tpr_util.go
test/e2e/e2eutil/wait_util.go
test/e2e/recovery_test.go
test/e2e/upgradetest/framework/framework.go

If the backup policy becomes nil in the new spec then the backup sidecar deployment, backup service and storage(if `CleanupBackupsOnClusterDelete` is set) should get deleted.
Should there be anything in the changelog for this?

cluster: delete backup manager's deployment, service and storage on spec change

---

test/e2e/framework/framework.go
test/e2e/recovery_test.go
test/e2e/restore_test.go

This field is not maintained anymore.
Let’s clean this up. When we merge PR like this next time, we should test and make sure everything works before merging it.

e2e: remove outdated EnvCloudProvider var

---

test/e2e/basic_test.go
test/e2e/e2eslow/disruptive_test.go

As part of https://github.com/coreos/etcd-operator/pull/1139
First commit from https://github.com/coreos/etcd-operator/pull/1149

*: move TestRestartOperator to e2eslow/disruptive_test.go

---

test/e2e/basic_test.go
test/e2e/cluster_status_test.go
test/e2e/recovery_test.go
test/e2e/resize_test.go
test/e2e/restore_test.go

fix https://github.com/coreos/etcd-operator/issues/1134
~~I have added another job "e2eslow-pr" just for PR CI. Mostly sequential/destructive tests.
The nightly master will still run all e2e in one job.~~
~~This PR separates some e2e tests into another package "e2eslow", which will be run as another job.~~
(fixed in other PRs)
Previously we use subtests to guard sequential from parallelizable tests. We have made all test under "e2e" parallelizable so we just parallelize them all. No need to use subtest any more. And we should remove subtest to achieve maximum parallelization.

*: parallelize e2e tests dramatically

---

CHANGELOG.md
doc/user/rbac.md
hack/ci/rbac_utils.sh

[skip ci]
After #1158 the operator needs another rbac rule to create events.
Also modified the rules for thirdpartyresources and storageclasses to encompass all verbs so we don't have to change them for later use cases.

rbac: add rules for events

---

cmd/operator/main.go
pkg/controller/controller.go
pkg/util/probe/readyz.go

The operator now creates an http endpoint to indicate its readiness to the kubelet and other components. The endpoint is set to ready right after the controller starts watching for cluster events.
TODO: Set the endpoint to unready if the controller exits or stops?

*: add readiness probe for operator pod

---

CHANGELOG.md
example/deployment-aws.yaml
example/deployment-s3-backup.yaml.template
example/deployment.yaml
version/version.go

release: 0.3.1

---

pkg/util/k8sutil/pod_util.go
test/e2e/e2eutil/wait_util.go
test/e2e/upgradetest/framework/framework.go

The upgradetest framework will now check and wait until the operator pod is ready via the readyz probe, for both `CreateOperator()` and `UpgradeOperator()`.
This way each test would not have to wait longer than necessary for the operator to first become ready while checking for cluster size via `WaitUntilSizeReached()`.
Stress testing for notably flaky tests in #1153

upgradetest: add readiness probe to wait for operator pod

---

test/e2e/e2eutil/wait_util.go
test/e2e/upgradetest/framework/framework.go
test/e2e/upgradetest/upgrade_test.go

Fix for #1176 
Also moved `WaitUntilPodReady()` outside from `CreateOperator()` so that the operator can be safely cleaned up incase a test fails due `WaitUntilPodReady()`.

upgradetest: replace WaitEtcdTPR with readiness

---

pkg/cluster/cluster.go
pkg/cluster/reconcile.go

We don’t have the “service” anymore since we use subdomains for etcd pods. This is leftover code that we forget to remove.

cluster: no need to delete service

---

test/e2e/upgradetest/framework/framework.go

[skip ci]
Should be part of https://github.com/coreos/etcd-operator/pull/1187 but somehow dismissed.

upgrade test: add dismissed change

---

README.md

Submit the pull request for the fix of issue 1188. 
fix https://github.com/coreos/etcd-operator/issues/1188

Issue 1188. Fix typo in README.md for getting the service URL.

---

CHANGELOG.md
pkg/cluster/upgrade.go
pkg/spec/cluster.go
pkg/util/k8sutil/k8sutil.go
pkg/util/k8sutil/pod_util.go
pkg/util/k8sutil/self_hosted.go

Cherry picks 00a11ca from https://github.com/coreos/etcd-operator/pull/1056 and resolves merge conflicts.
Fixes https://github.com/coreos/etcd-operator/issues/1156.

Add custom image URL

---

test/e2e/basic_test.go
test/e2e/e2eslow/disruptive_test.go
test/e2e/e2eutil/wait_util.go

`waitSizeReachedWithAccept()` now waits until the cluster TPR shows the desired number of ready members.
`WaitUntilPodSizeReached` is needed for the tests `TestPauseControl` and `TestRestartOperator` to directly check the number of pods, since the TPR won't be updated while the operator is paused/deleted. 
fixes #1060

e2eutil/wait_util: wait until etcd member is ready

---

test/e2e/upgradetest/upgrade_test.go

It's not good practice to put method call within if. 
This is because 1. line is too long, 2. it could potentially shade variables.
We should have a good code style for this.

code_style: don't put method call within if

---

glide.lock
glide.yaml
pkg/cluster/error_test.go
pkg/cluster/member.go
pkg/cluster/reconcile.go
pkg/util/etcdutil/member.go

ref: https://github.com/coreos/etcd-operator/issues/1200#issuecomment-309193926
This PR makes fatal error a type and uses “pkg/errors” to wrap the fatal error. It also rewrite the isFatalError() func to unwrap the cause as detection.

cluster: fatal error should be wrapped

---

test/e2e/e2eutil/wait_util.go
test/e2e/upgradetest/upgrade_test.go

Since `WaitUntilSizeReached()` looks at the TPR's `Status.Members.Ready` field to calculate the size of the of the cluster, `WaitUntilMembersWithNamesDeleted()` waits until the pods killed by `KillMembers()` are no longer present in the ready members field.
~fixes #1204~
Note: This can't be used after `KillMembers()` in `TestDisasterRecovery` because disaster recovery recreates members with the same names as the original cluster. So looking at the TPR's ready members there is no way to tell which members are from the original cluster and which ones are from the recreated cluster. So we can't wait for the old pods to be deleted just by looking at ready members.

upgradetest: wait for killed members to be deleted

---

test/e2e/upgradetest/upgrade_test.go

fix for #1204
Using `WaitUntilPodSizeReached ()` to check the pods size instead of  `WaitUntilSizeReached()` to check the ready members, should prevent `TestDisasterRecovery` from mistakenly querying one of the terminating pods.

upgradetest: wait for pod size instead of ready member size

---

pkg/cluster/backupstorage/s3.go
pkg/util/constants/constants.go

fix this based on discussion in https://github.com/kubernetes-incubator/bootkube/issues/581#issuecomment-310520684

operator: fix aws config dir to /var/tmp/etcd-operator/aws

---

test/e2e/e2eslow/tls_test.go
test/e2e/e2eutil/util.go

We shouldn't have two tests have the same cluster name to guard async deletion.
But we can't use GenerateName because we need it explicit to create certs.

e2e: fix tls tests interference

---

test/e2e/e2eutil/wait_util.go
test/e2e/recovery_test.go

Use `WaitUntilPodSizeReached()` to check the pods size, instead of `WaitUntilSizeReached()` which looks at the TPR's ready members, in the tests `TestOneMemberRecovery` and `TestDisasterRecovery`.
Before this the tests would mistakenly assume that the cluster had been recovered to size 3 after killing one or all members. The issue being that there is a delay between killing a member pod, and the cluster TPR getting updated to reflect that the removal of that member.
We fixed the same problem for other tests that use `KillMember()` in upgradetest and e2e tests in #1208 and #1101

e2e/recovery_test: wait for pod size instead of ready member size

---

pkg/cluster/cluster.go

Changes #1210 to split the readable logs into multiple lines, so that each line has the field `cluster-name=example-etcd-cluster` appended to it for ease of inspection of the logs.
Visually the changes look like so:
```
Spec:
{
"size": 3,
"baseImage": "quay.io/coreos/etcd",
"version": "3.1.8"
}
```
now looks like
```
time="2017-06-30T22:32:12Z" level=info msg="{" cluster-name=example-etcd-cluster pkg=cluster
time="2017-06-30T22:32:12Z" level=info msg="    "size": 3," cluster-name=example-etcd-cluster pkg=cluster
time="2017-06-30T22:32:12Z" level=info msg="    "baseImage": "quay.io/coreos/etcd"," cluster-name=example-etcd-cluster pkg=cluster
time="2017-06-30T22:32:12Z" level=info msg="    "version": "3.1.8"" cluster-name=example-etcd-cluster pkg=cluster
time="2017-06-30T22:32:12Z" …
```

cluster: split multi line logs into individual messages

---

test/e2e/upgradetest/upgrade_test.go

This is the only failing test in upgrade e2e now.
Same issue as https://github.com/coreos/etcd-operator/pull/1251 .

upgrade_e2e: fix restore same name test

---

test/e2e/upgradetest/framework/framework.go

Upgrade test flakes caused by that even though two tests now uses different names for deployment , their endpoint locks still share the same name.
We could simply delete the endpoint after deleting the operator in each test.

upgrade_e2e: delete endpoint after delete operator

---

pkg/util/retryutil/retry_util.go

This is blocking other people's PRs. For example, Haseeb is constantly seeing this failure. I'm picking it out from https://github.com/coreos/etcd-operator/pull/1275 to merge early to unblock other PRs.

retry: fix assumption

---

doc/alpha-features.md
pkg/util/k8sutil/k8sutil.go

also fix the port naming issue
fix https://github.com/coreos/etcd-operator/issues/1257

*: enable tolerate unready in service

---

CHANGELOG.md
cmd/operator/main.go
pkg/cluster/cluster.go
pkg/cluster/self_hosted.go
pkg/debug/debug_logger.go
pkg/util/k8sutil/pod_util.go

Partially addresses #1205 
The operator will now audit the following actions for a self-hosted cluster to a hostPath volume:
- Create an etcd pod
- Delete an etcd pod
- A spec update to the cluster
- Deleting a failed cluster
To enable the auditing a hostPath volume must be mounted to the mountPath `/var/tmp/etcd-operator` as shown below. The hostPath itself can be anything but should ideally be `/var/tmp` so the operator container can write to the volume even when running as non-root.
```
spec:
containers:
- name: etcd-operator
volumeMounts:
- mountPath: /var/tmp/etcd-operator
name: audit-volume
volumes:
- name: audit-volume
hostPath:
path: /var/tmp/
```
The audit file will be named `<cluster-name>.log` .
If no volume is mounted at the desired mountPath the operator will not audit and …

*: audit operator actions to hostPath volume

---

pkg/util/k8sutil/k8sutil.go

Now that etcd will retry resolving DNS names in 3.1+, we don't need to 5s sleep anymore

k8sutil: get rid of 5s sleep in etcd 3.1+

---

test/e2e/e2eutil/spec_util.go
test/e2e/e2eutil/wait_util.go
test/e2e/framework/framework.go
test/e2e/upgradetest/framework/framework.go
test/e2e/upgradetest/upgrade_test.go

The framework for the e2e tests now uses `WaitUntilOperatorReady()` while setting up the etcd operator instead of waiting for the TPR, similar to the upgrade test framework.

e2e: replace WaitEtcdTPRReady with WaitUntilOperatorReady

---

CHANGELOG.md
doc/user/upgrade/upgrade_guide.md

The CHANGELOG highlights the transition to CRD.
The upgrade guide lists steps on how to upgrade to using CRD by recreating the new cluster from backup.
Testing out the upgrade guide steps out manually to make sure they work.

*: update CHANGELOG and upgrade_guide for TPR to CRD migration

---

CHANGELOG.md
pkg/backup/backup.go
pkg/util/constants/constants.go

For larger databases, a snapshot can take much longer than the 5 seconds previously given. This approach is not exactly elegant, but for the snapshot in the backup, give it a larger timeout.

backup: increase default snapshot timeout

---

doc/user/op_guide.md

as downstream in https://github.com/coreos-inc/coreos-pages/pull/1773
[skip ci]

doc/user/op_guide: Fix typo verb tense create vs create

---

doc/user/upgrade/upgrade_guide.md

This PR fixes upgrade guide TRP cleanup section.
cc: @hongchaodeng

Fix TRP name in upgrade guide

---

pkg/backup/version.go

Currently when I try to restore etc 3.2 backup (e.g. during TPR->CRD upgrade) I get an error that "version 3.2 is not compatible with version 3.2".
This PR adds 3.2 to backup/restore compatibility matrix.

Add support for etcd 3.2 to backup version matrix

---

CHANGELOG.md
pkg/cluster/backup_manager.go
pkg/cluster/backupstorage/pv.go
pkg/util/k8sutil/backup.go
test/e2e/cluster_status_test.go
test/e2e/e2eutil/spec_util.go
test/e2e/recovery_test.go
test/e2e/restore_test.go
test/e2e/upgradetest/upgrade_test.go

Adds a `StorageClass` field to the `BackupPolicy` spec. Fixes #953.
Although I've verified this works, I didn't add any e2e tests because I wasn't sure whether your CI cluster supports any custom StorageClasses.

Implement StorageClass spec field

---

doc/design/persistent_volumes_etcd_data.md

Since the final scope is to achieve a durable etcd cluster (#1323) I put in this proposal the changes split in two parts (as requested). IMHO putting only the first part is not really useful because it will hide many detail of the overall idea. For example putting RestartPolicy to Always can bring a little gain for part 1 but could be not useful (or add more issues) for part 2.
I also added some notes since the use of persistence volume requires the knowledge of other k8s logic (https://github.com/kubernetes/community/blob/master/contributors/design-proposals/pod-safety.md) because etcd operator is acting as a pod controller.
[skip ci]

doc: persistent volumes for etcd data proposal

---

pkg/spec/backup.go
pkg/spec/cluster.go

As requested by @hongchaodeng here (https://github.com/coreos/etcd-operator/pull/1349#issuecomment-321013872) I opened this PR to discuss only spec changes to add pv support for etcd data.
I wanted to propose to directly use StorageClass in the spec instead of the `--pv-provisioner` option but I noticed this has been already accepted during my vacations in #1361. So I used it, moving it from spec/backup.go to spec/cluster.go and added PVSource also to PodPolicy.
This patch adds the initial spec changes (without implementation) to
support storing etcd data inside a persistent volume.
The PVSource type used by the backups policy is now shared between
backups and pod policies.
Since this only a spec change the required spec validation isn't part of this patch.

spec: add PVSource to PodPolicy

---

CHANGELOG.md
pkg/backup/abs/abs.go
pkg/backup/backup.go
pkg/backup/env/env.go
pkg/cluster/backup_manager.go
pkg/cluster/backupstorage/abs.go
pkg/spec/backup.go
pkg/util/k8sutil/backup.go

(Re-issue of https://github.com/coreos/etcd-operator/pull/1369)
TODO:

feat(abs): add operator logic

---

CHANGELOG.md
pkg/spec/cluster.go
pkg/util/k8sutil/pod_util.go

By default, Kubernetes will mount a service account token into the etcd
pods. This allows users to disable this via the pod-policy.

pod-policy: add automountServiceAccountToken to the pod policy

---

doc/user/rbac.md

In order to create an `etcd` cluster with TLS enabled, the service account being used needs access to the `etcd-client-tls`, `etcd-peer-tls` and `etcd-server-tls` secrets.
---
Since one needs `secrets` for both TLS and S3 I don't know whether it would be preferable to include `secrets` right away here:
https://github.com/coreos/etcd-operator/blame/master/doc/user/rbac.md#L81
Any thoughts?

doc: add a note on TLS to the RBAC docs

---

README.md
doc/user/resource_labels.md
pkg/util/k8sutil/backup.go
pkg/util/k8sutil/k8sutil.go

@hongchaodeng I've listed out all the resource labels I could see but PTAL and let me know if we need to align them better.
Only the backup sidecar pod uses the `app=etcd_backup_tool` label which I think was required to select it in e2e testing.

*: document resource labels

---

pkg/cluster/cluster.go
pkg/cluster/reconcile.go
pkg/util/k8sutil/events_util.go

Part of #1412 
With this `kubectl describe etcdcluster <cluster-name>` shows the events like:
```
Events:
FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
---------	--------	-----	----				-------------	--------	------			-------
30s		30s		1	etcd-operator-3106627829-lkfgx			Normal		New Member Added	New member example-etcd-cluster-0000 added to cluster
22s		22s		1	etcd-operator-3106627829-lkfgx			Normal		New Member Added	New member example-etcd-cluster-0001 added to cluster
12s		12s		1	etcd-operator-3106627829-lkfgx			Normal		New Member Added	New member example-etcd-cluster-0002 added to cluster
```

*: create event for new member added

---

cmd/backup/main.go
cmd/operator/main.go
pkg/util/constants/constants.go
pkg/util/k8sutil/backup.go
pkg/util/k8sutil/events_util.go
test/e2e/framework/framework.go
test/e2e/upgradetest/framework/framework.go

Add constants for using `MY_POD_NAME` and `MY_POD_NAMESPACE` in different places.

*: use consts for operator pod name and namespace

---

pkg/cluster/reconcile.go
pkg/util/k8sutil/events_util.go

Added events for removing a member, and replacing a dead member.
The following events are generated from:
- Creating a 3 member cluster
- Scaling cluster size to 4 members
- Deleting the pod of the 4th member `example-etcd-cluster-0003`
- Scaling cluster size back to 3 members
```
Events:
FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
---------	--------	-----	----				-------------	--------	------			-------
7m		7m		1	etcd-operator-3106627829-m7m56			Normal		New Member Added	New member example-etcd-cluster-0000 added to cluster
7m		7m		1	etcd-operator-3106627829-m7m56			Normal		New Member Added	New member example-etcd-cluster-0001 added to cluster
7m		7m		1	etcd-operator-3106627829-m7m56			Normal		New Member Added	New member example-etcd-cluster-0002 added to cluster …
```

*: add events for remove member and replace dead member

---

pkg/cluster/upgrade.go
pkg/util/k8sutil/events_util.go

Addresses #1412 
Events for upgrade now look like:
```
Events:
FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
---------	--------	-----	----				-------------	--------	------			-------
2m		2m		1	etcd-operator-3106627829-813mj			Normal		New Member Added	New member example-etcd-cluster-0000 added to cluster
1m		1m		1	etcd-operator-3106627829-813mj			Normal		New Member Added	New member example-etcd-cluster-0001 added to cluster
1m		1m		1	etcd-operator-3106627829-813mj			Normal		New Member Added	New member example-etcd-cluster-0002 added to cluster
1m		1m		1	etcd-operator-3106627829-813mj			Normal		Member Upgraded		Member example-etcd-cluster-0000 upgraded from 3.1.8 to 3.1.9
56s		56s		1	etcd-operator-3106627829-813mj			Normal		Member Upgraded		Member …
```

*: add member upgraded event

---

README.md

We're experimenting with the etcd operator on staging. We're only using it with reproducible data, but we wanted to test the backups all the same, and discovered that v2 data isn't backed up.
This is fine, since most people use the v3 API now anyway.
However, as a cluster operator I would like to disable v2, so consider this PR my +1 to #1315

Add caveat regarding v2 API data.

---

CHANGELOG.md
pkg/cluster/cluster.go
pkg/cluster/cluster_test.go

fix https://github.com/coreos/etcd-operator/issues/1329
In some case we might ignore cluster update for some immutable fields,
e.g. PodPolicy update. But local cluster object isn't updated and
it might keep failing on version conflict on status report.

cluster: fix ignore cluster update

---

cmd/backup/main.go
cmd/etcd-backup-operator/main.go
cmd/operator/main.go
glide.lock
glide.yaml
pkg/backup/abs.go
pkg/backup/backup.go
pkg/backup/file.go
pkg/backup/http.go
pkg/backup/s3.go
pkg/backup/util.go
pkg/chaos/chaos.go
pkg/cluster/backup_manager.go
pkg/cluster/cluster.go
pkg/controller/controller.go
pkg/debug/debug_logger.go
pkg/garbagecollection/gc.go
test/e2e/e2eslow/main_test.go
test/e2e/framework/framework.go
test/e2e/main_test.go
test/e2e/upgradetest/main_test.go

Changed package name from github.com/Sirupsen
to github.com/sirupsen to reflect upstream package name change.
Changed go files to new import for logging.
Changed glide.lock and glide.yaml for new package name

Changed github.com/Sirupsen to github.com/sirupsen

---

glide.lock

The hash in glide.lock was out of date causing the following warning on doing `glide install --strip-vendor`
```
Lock file may be out of date. Hash check of YAML failed. You may need to run 'update'
```
Most probably it was caused by not updating the lock file properly in #1474 
https://github.com/coreos/etcd-operator/pull/1474/files#diff-f16a80eae23d5b298c2652448ec420cfR1

glide: update hash of glide.lock

---

README.md

The link of User Aggregated API Servers has changed to https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/aggregated-api-servers.md.
[skip ci]

README.md: fix broken aggregated api server link

---

cmd/backup/main.go
pkg/backup/backend/s3.go
pkg/backup/backup.go
pkg/backup/backup_test.go
pkg/backup/http.go

Previously, controlling logic and snapshot retrieving/storing logic are coupled together into a struct called backup.
This pr separates controlling logic and snapshot retrieving/storing logic out of backup into BackupController and BackupManager:
BackupController is responsible for controlling when to perform backup.
BackupManager is responsible for retrieving/storing backup.

*: split backup into BackupController and BackupManager.

---

pkg/backup/backup.go
pkg/cluster/backupstorage/s3.go

This pr exposes SetupAWSConfig in backupstorage/s3.go so that etcd backup operator can use it to set up aws credentials.
In addition, it creates NewBackupManager to construct BackupManager so that BackupManager's private fields don't have to be exposed.

*: expose setupAWSConfig and construct BackupManager with NewBackupManager

---

cmd/restore-operator/main.go
pkg/controller/restore-operator/controller.go
pkg/controller/restore-operator/operator.go
pkg/controller/restore-operator/sync.go

this pr is meant to keep naming consistent on using keyword restore operator in pkg/controller.

pkg/controller: rename restorecontroller to restore-operator

---

cmd/backup/main.go
pkg/backup/backup.go
pkg/backup/http.go

Separate controller.Run() from startHTTP() allows backup to have a choice
on what to run and not to run.
This is important because backup will be adding a flag to enable only
serve backup http requests.

*: expose startHTTP

---

cmd/backup/main.go
pkg/backup/backup.go
pkg/backup/http.go

We want to reuse the backup binary to do:
- backend credentials setup
- TLS setup (potentially)
- HTTP
This is the first step to provide a feature gate and
simply disable periodic backup logic.

backup: add feature-gate to serve backup only

---

CHANGELOG.md
cmd/backup/main.go
cmd/backup/main_test.go
pkg/backup/backup.go
pkg/backup/env/env.go

backup now parses BackupSpec from backup_types.go. restore controller will create backup service based on BackupSpec.
NewBackupController function now takes a BackupControllerConfig instead of individual parameters to simplifies NewBackupController input. it also removes the dependency of NewBackupController on input parameter ClusterSpec.
added test on parsing the env specs.
added backup binary behavior change to backup log.

*: backup now support parsing backupSpec from backup_types.go

---

CHANGELOG.md
pkg/cluster/cluster.go
pkg/controller/controller.go
pkg/controller/informer.go

~The backup policy should be validated not only when the cluster spec is created but also when the cluster spec's backup policy is updated.~
The cluster spec is now validated in the controller. Any event with an invalid spec is ignored and logged.

*: ignore event with invalid cluster spec at the controller

---

cmd/operator/main.go
pkg/apis/etcd/v1beta2/backup.go
pkg/controller/controller.go
pkg/controller/informer.go
test/e2e/framework/framework.go
test/e2e/upgradetest/framework/framework.go

Addresses #1527 
The default behavior of the etcd-operator is now to not create global resources (CRD, StorageClass). This is governed by the flag `no-global-cluster-resource` which is true by default.
In this default mode the `--pv-provisioner` flag will have no effect. Any backup policy of type `PV` without a `StorageClass` field will be invalid because the operator will not create any StorageClass resource.
To revert back to the old behavior of the operator the flag `no-global-cluster-resource` needs to be set to false.

*: add flags to not create global resources CRD and StorageClass

---

pkg/controller/backup-operator/s3_backup.go
pkg/controller/controllerutil/util.go

creation of s3backend can be shared for both backup operator and restore operator.
moving it out to a util pkg allows code reuse.

*: move creation of s3backend to a util pkg

---

pkg/controller/controller.go
pkg/controller/informer.go
pkg/util/k8sutil/crd.go

If the `create-crd` flag is false then the operator should also not be **waiting** for the crd to become ready since it does not have the rbac permissions to get a crd.
So if `create-crd` is false then this will skip the `initCRD()` altogether.

controller: fix CreateCRD condition check

---

hack/build/backup-operator/push

backup operator build path is hack/build/backup-operator instead of  hack/build/etcd-backup-operator.

hack: fix push path

---

test/e2e/cluster_status_test.go
test/e2e/framework/framework.go
test/e2e/recovery_test.go
test/e2e/restore_test.go
test/e2e/upgradetest/framework/framework.go
test/e2e/upgradetest/main_test.go
test/e2e/upgradetest/upgrade_test.go

Addresses #1527 
Every test that was using the PVBackupPolicy will now use the storage class created by its framework at the start.
The operator being tested on will not create the storage class itself.
The storage class created by the framework will not be cleaned up at the end since it is a cluster resource and it could be in use by other tests on the cluster.

e2e: tests will use the storage class created by the framework

---

doc/user/rbac.md
example/rbac/cluster-role-binding-template.yaml
example/rbac/cluster-role-template.yaml
example/rbac/role-binding-template.yaml
example/rbac/role-template.yaml
hack/ci/rbac_utils.sh

Addresses #1527 
This PR updates the RBAC setup guide to explain how to setup RBAC with either a ClusterRole or Role, depending on the `create-crd` flag.
Added RBAC templates at `example/rbac` so that both the RBAC doc and `hack/ci/rbac_utils.sh` use the same permissions.
The rbac_utils still sets up RBAC with a ClusterRole since our e2e tests test the etcd-operator for the default mode of `--create-crd=true`.

*: update and unify rbac doc and rbac utils with rbac templates

---

CHANGELOG.md
doc/user/upgrade/upgrade_guide.md

[skip ci]
Added the section for the upgrade guide to `v0.6.1`.
The section explains how to correctly set the storage class name for clusters using a backup policy with PV storage with no storage class name.
Since the storage class is only needed when creating a new cluster this is not a breaking change for users with existing clusters and is required more for the spec to be consistent with the new operator behavior.
So the CHANGELOG does not say **Breaking Change**.

upgrade_guide.md: add section for 0.6.1

---

doc/user/op_guide.md
doc/user/rbac.md
example/rbac/create_role.sh

Streamline the getting started workflow for developers using k8s 1.7+ with a single command to setup RBAC and clearly document it in the getting started docs.

doc: Add script to streamline RBAC setup

---

pkg/util/k8sutil/k8sutil.go

All k8sutil methods follow re-entry-ness . It's part of the convention.
Code cleanup.

k8sutil: ignore alreadyExist on createService

---

pkg/controller/restore-operator/sync.go

group handling restore cr into a function called handleCR
avoid processing cr twice if it has status. since updating cr's status triggers
the cr the be queued again, don't process the cr if that's the case.

controller/restore-operator: don't process cr if it has a status

---

pkg/controller/backup-operator/sync.go

if cr has a status, it means that this cr has been process before.
In that case, don't process the cr again.
reportBackupStatus takes in berr instead of err to differentiate input err vs internal error.

controller/backup-operator: don't process cr if it has a status

---

doc/design/restore_operator.md
pkg/apis/etcd/v1beta2/restore_types.go
pkg/cluster/cluster.go
pkg/controller/backup-operator/sync.go
pkg/controller/restore-operator/controller.go
pkg/controller/restore-operator/operator.go
pkg/controller/restore-operator/sync.go

prepareSeed() is changed to:
- create EtcdCluster CR but spec.paused=true and status.phase="Running" .
- Expect etcd operator to setup the services
- create seed member that would restore data from backup
- ownerRef to above EtcdCluster CR
- update EtcdCluster CR spec.paused=false
- etcd operator should pick it up and scale the etcd cluster

*: restore operator prepares seed and etcd operator takes over

---

cmd/operator/main.go
doc/user/backup_config.md
pkg/apis/etcd/v1beta2/backup.go
pkg/cluster/backup_manager.go
pkg/cluster/backup_manager_test.go
pkg/cluster/cluster.go
pkg/controller/controller.go
pkg/controller/informer.go
pkg/util/constants/constants.go
pkg/util/k8sutil/backup.go
test/e2e/framework/framework.go
test/e2e/upgradetest/main_test.go

Removed all logic related to the `pv-provisioner` and `create-storage-class` flags.
The backup policy validation at the controller now includes checking that storage class must be set, else the event is not handled with a warning.
```
fail to handle event: invalid cluster spec. please fix the following problem with the cluster spec: PV backup must have a storage class set
```

*: remove pv-provisioner and create-storage-class flags

---

pkg/apis/etcd/v1beta2/cluster.go
pkg/apis/etcd/v1beta2/register.go
pkg/controller/controller.go
pkg/controller/informer.go
pkg/util/k8sutil/crd.go
pkg/util/k8sutil/events_util.go
test/e2e/e2eutil/spec_util.go

CreateCRD now creates CRD based on crd name, crd kind, crd plural, and shortName.
WaitCRDReady now waits crd based on crd name.
Replace usage of keyword CRDName and related CRD defs to be prefixed with the keyword EtcdCluster.

*: generalize CreateCRD and WaitCRDReady

---

pkg/util/k8sutil/crd.go

ShortNames can't be empty. Or else kubernetes api server complains:
```
spec.names.shortNames[0]: Invalid value: "": a DNS-1035 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')"
```

util: only add shortName if it is not empty

---

hack/test
test/e2e/framework/framework.go

updates fmt_build to push all operators into one image.
enables e2e framework to run/delete etcd backup operator.

*: support backup operator creation in e2e

---

test/e2e/backup_test.go
test/e2e/e2eutil/spec_util.go

add an e2e test for etcd backup operator:
1. create etcd cluster.
2. invoke a backup cr for the etcd cluster.
3. verify that backup status shows succeeded.
4. verify that s3 has the object from s3path of backup status.

e2e: add etcd backup operator test

---

pkg/backup/reader/reader.go
pkg/backup/reader/s3_reader.go

Adresses #1588 
Add a reader interface and s3 reader that the restore-operator can use to read and serve backup files to the seed member pod.
This will replace the use of the backup_server in the restore operator
https://github.com/coreos/etcd-operator/blob/master/pkg/controller/restore-operator/http.go#L62-L68

reader: add s3 reader for reading backup files

---

pkg/controller/restore-operator/http.go
pkg/controller/restore-operator/operator.go
pkg/controller/restore-operator/sync.go

Part 1 of 2 of #1596
Changes the restore-operator to track a restore via restore CR name instead of spec.BackupSpec.ClusterName.

controller/restore-operator: use restore name instead of cluster name

---

pkg/backup/writer/s3_writer.go
pkg/backup/writer/writer.go

Write() should return the size of written file. 
The size is required in backup manager to construct backup status.

writer: Write now returns backup size

---

pkg/apis/etcd/v1beta2/restore_types.go
pkg/controller/restore-operator/http.go

Addresses #1588 
Part 2 of #1596 
restore-operator now uses the `S3RestoreSource` of a restore CR to read and return a backup via the s3Reader.
Also fixed the `RestoreSource ` to be embedded so the s3 field can be specified directly in the backup CR like:
```
spec:
clusterSpec:
size: 3
version: "3.1.8"
s3:
path: jenkins-etcd-operator/test-prefix/v1/e2e-local/s3-cluster-backup/3.1.8_0000000000000001_etcd.backup
awsSecret: aws
```

controller/restore-operator: use s3Reader to read backup

---

pkg/backup/backup_manager.go
pkg/controller/backup-operator/s3_backup.go

* backup manager now can write backup to a specific path prefix with the `SaveSnapWithPrefix` function.
* add NewBackupManagerFromWriter factory function to create a BackupManager based on backup writer.
* backup operator uses `SaveSnapWithPrefix` to save snapshot.

*: add writer to backup manager 

---

pkg/apis/etcd/v1beta2/restore_types.go
pkg/backup/backupapi/http.go
pkg/controller/restore-operator/sync.go

Addresses #1588 
The restore operator now creates an etcd cluster CR whose name is the restore-name.
The seed member for that cluster uses only the restore-name in its query.
Also fixed a race condition where the restore operator was updating the etcdcluster CR without getting the latest version first. This would cause the following error:
```
Operation cannot be fulfilled on etcdclusters.etcd.database.coreos.com "restore-s3-cluster-backup": the object has been modified; please apply your changes to the latest version and try again
```

*: change seed member query for restore-operator

---

pkg/apis/etcd/v1beta2/restore_types.go
pkg/apis/etcd/v1beta2/zz_generated.deepcopy.go

Remove `BackupSpec` now that restore CR uses `RestoreSource`.

*: remove BackupSpec from restore CR spec

---

cmd/restore-operator/main.go
example/rbac/cluster-role-template.yaml
example/rbac/role-template.yaml
pkg/util/constants/constants.go
test/e2e/framework/framework.go

Addreses #1611 
The e2e framework will now setup and teardown the restore-operator pod and service.
Additionally, the RBAC permissions needed updating to include `etcdbackups` and `etcdrestores` so that the e2e tests setup the required permissions for backup-operator and restore-operator. 
Our GKE jenkins cluster runs does not require RBAC so this was not detected when the backup-operator e2e test was added.

*: setup restore-operator in e2e framework

---

test/e2e/backup_test.go
test/e2e/e2eutil/spec_util.go

Addresses #1611 
The e2e test for the restore operator does the following:
- Create an EtcdRestore CR using the awsSecret and S3 path passed in
-  Wait until the CR status has `succeeded=true`
- Verify that the restored etcd cluster reaches the desired size
The restore e2e test needs the S3 path to be set. To do this the backup and restore tests are run sequentially:
- The backup operator test is `testEtcdBackupOperatorForS3Backup` is run first.
- That will return the S3 path if successful.
- The restore operator test runs after that using the S3 path returned by the previous test.

e2e: add e2e test for restore operator

---

cmd/backup-operator/README.md

readme: fix typos in backup-operator/README.md

---

hack/test

ref: https://github.com/coreos/etcd-operator/issues/1626
minio and azurite act as a mock backend storage for S3 and ABS. it is used
for s3/abs backend unit testing.
removing those is part of the effort to remove s3/abs backend from etcd opreator.

hack/test: remove init for minio and azurite

---

hack/ci/run
test/e2e/framework/framework.go

previously `AWS_TEST_ENABLED` flag indicates whether to run tests that consume AWS resource or not.
Now, all tests including the the AWS must run regardless.

e2e: always run aws tests in e2e

---

test/e2e/backup_test.go
test/e2e/e2eutil/spec_util.go
test/e2e/framework/framework.go

remove setupAWS from framework.
add aws env check for backup_test.go.
construct s3client using s3factory.NewClientFromSecret to create s3 client in backup_test instead of using env variables.

e2e:  remove setupAWS from framework and check AWS envs for backup_test

---

hack/build/backup-operator/build
hack/build/operator/build
hack/build/restore-operator/build
hack/lib/build.sh

remove go install from build scripts.
go build for operators can now take-in extra flags.
refactor go_build as a standalone lib in hack/lib.

*: Improve go build

---

test/pod/Dockerfile
test/pod/README.md
test/pod/build
test/pod/run-test-pod
test/pod/test-pod.yaml

[skip ci]
Resolves part of #1640 
The `run-test-pod` script now waits until the test-pod is running, prints out its logs, reports if the pod succeeded or failed and deletes the test-pod.
Additionally a few minor fixes.
/cc @hongchaodeng @fanminshi

test/pod: have run-test-pod wait and cleanup pod

---

test/e2e/framework/framework.go
test/e2e/upgradetest/framework/framework.go
test/e2e/upgradetest/main_test.go

ref: #1626 
The test frameworks(e2e and upgrade) no longer need to create the StorageClass since there are no PV backup tests.
With the [current rbac permissions](https://github.com/coreos/etcd-operator/blob/master/example/rbac/cluster-role-template.yaml) the tests should have failed up until now due to a lack of permissions for storageclass but since GKE has no rbac, the tests would run fine.

e2e: remove storage class creation from frameworks

---

test/pod/README.md
test/pod/run-test-pod

[skip ci]
ref: #1640 
The run-test-pod script now sets up RBAC before running the test-pod.

test/pod: setup rbac in run-test-pod

---

test/pod/run-test-pod

[skip ci]
ref: #1640 
The test-pod could fail to become running due to a bad image name or some other issue. So a timeout is needed in run-test-pod otherwise it keeps waiting forever.

test/pod: timeout if test-pod does not become running

---

README.md
cmd/backup-operator/doc.go
cmd/restore-operator/doc.go

add doc and warning to clarify that  backup/restore operator are example implementation and not for production usage.
[skip ci]

*: clarify backup/restore operator usage

---

doc/design/dynamic_tls.md

[skip ci]
ref: https://github.com/coreos/etcd-operator/issues/1617, https://github.com/coreos/etcd-operator/issues/1465

doc: dynamic tls design

---

pkg/util/k8sutil/k8sutil.go
pkg/util/k8sutil/pod_util.go
pkg/util/k8sutil/self_hosted.go

fix https://github.com/coreos/etcd-operator/issues/1680
Instead of using "/bin/sh", it splits the commands directly into ["etcd", "--name=xxx", ...]
Based on my manual testing, etcd pods are deleted based on SIGTERM signal.
Note that this does not change self-hosted case.

k8sutil: get rid of /bin/sh in app etcd pod

---

doc/user/install_guide.md
doc/user/walkthrough/backup-operator.md
doc/user/walkthrough/restore-operator.md

[skip ci]
Add setting up RBAC and etcd operator as a prerequisite to backup/restore doc.
fix https://github.com/coreos/etcd-operator/issues/1683

doc: Improve backup/restore doc

---

pkg/apis/etcd/v1beta2/backup_types.go
pkg/backup/backup_manager.go
pkg/controller/backup-operator/s3_backup.go
pkg/controller/backup-operator/sync.go
pkg/util/k8sutil/tls.go
test/e2e/backup_test.go
test/e2e/e2eutil/spec_util.go
test/e2e/e2eutil/tls.go

add ClientTLSSecret to backup spec; it is kubernete secret that contains client tls certs.
backup operator uses the ClientTLSSecret to  construct a TLS enabled 
etcd client for retrieving etcd snapshot.
ref: https://github.com/coreos/etcd-operator/issues/1495

*: support tls for backup operator

---

test/e2e/backup_test.go
test/e2e/e2eslow/tls_test.go
test/e2e/e2eutil/tls.go

fixes: #1700 
The framework now correctly seeds the random number generator.
The backup test cleans up its TLS secrets as well.
The error from executing commands is now wrapped as well in the tls util functions.

e2e: fix tls secret creation and cleanup in tests

---

hack/build/e2e/build
hack/build/e2e/builder/Dockerfile
hack/build/e2e/builder/build
hack/build/operator/build
test/pod/build
test/pod/run-test-pod

[skip ci]
The script `hack/build/e2e/build` builds all the binaries and images needed for e2e testing.
- operator image
- test-pod image
- logcollector binary
The script builds all the binaries inside a container whose image is defined under `hack/build/e2e/operator-builder`. (go 1.9,bash,git and dep)
This removes the dependence on the `hack/ci/run` script during testing.
This script would be run as:
```
OPERATOR_IMAGE=<opeartor-image> TEST_IMAGE=<test-pod-image> hack/build/e2e/build
```

*: combine build steps for e2e

---

CHANGELOG.md
pkg/apis/etcd/v1beta2/cluster.go
pkg/apis/etcd/v1beta2/zz_generated.deepcopy.go
pkg/util/k8sutil/k8sutil.go
pkg/util/k8sutil/pod_util.go
pkg/util/k8sutil/self_hosted.go

No etcd pod will have service account token mounted by default.
ref: https://github.com/coreos/etcd-operator/issues/1719

ClusterSpec: remove PodPolicy.AutomountServiceAccountToken

---

CHANGELOG.md
README.md
doc/user/spec_examples.md
doc/user/walkthrough/backup-operator.md
doc/user/walkthrough/restore-operator.md
example/etcd-restore-operator/restore_cr.yaml
example/example-etcd-cluster.yaml
pkg/apis/etcd/v1beta2/cluster.go
pkg/apis/etcd/v1beta2/restore_types.go
pkg/backup/backup_manager.go
test/e2e/backup_test.go
test/e2e/basic_test.go
test/e2e/e2esh/self_hosted_test.go

etcd 3.2.11 contains better TLS messages and bug fixes:
https://github.com/coreos/etcd/releases/tag/v3.2.11
Better update to it.

*: bump default etcd version to 3.2.11

---

pkg/apis/etcd/v1beta2/cluster.go

We have deprecated BaseImage. But it is still showing on `kubectl get etcd`.
Fixing that.
ref: https://github.com/coreos/etcd-operator/issues/1719

apis/etcd: omitempty tag for Repository and BaseImage

---

hack/build/e2e/build
hack/build/logcollector/Dockerfile
test/pod/Dockerfile
test/pod/run-test-pod

The logcollector is now pre-built as an image at `gcr.io/coreos-k8s-scale-testing/logcollector` and `run-test-pod` now runs the logcollector in container from that image.

*: run logcollector in container from pre-built image

---

pkg/apis/etcd/v1beta2/cluster.go
test/e2e/e2esh/self_hosted_test.go
test/e2e/e2eutil/spec_util.go

When we bump the etcd version to 3.2, the images were only available on gcr.io . But now it is added on quay.io .
We should better use quay.io and do a bug-fix release for it. In this way we can keep it compatible to work for 3.1 versions etcd.

*: change gcr.io images to quay.io

---

hack/build/e2e/docker_push
hack/ci/run2
test/pod/run-test-pod

The test-pod spec is now generated from the template in `hack/ci/run2` and passed to `run-test-pod` to use.

test/pod: decouple pod template and run script

---

doc/design/cluster_tls.md

I was reading through the cluster TLS design doc and noticed a few typos. Fixed them.
[skip ci]

doc: fix typos in cluster TLS design doc

---

hack/ci/run_e2e
test/pod/README.md
test/pod/test-pod-templ.yaml

@hongchaodeng PTAL
Already tested the upgrade tests against my own branch
https://jenkins-etcd.prod.coreos.systems/view/operator/job/etcd-operator-upgrade/243/console
Forgot to archive the logs for that run. Update the jenkins job to archive the logs now.

*: support running upgrade tests in test-pod

---

hack/ci/run_e2e

Defaulting all possible env values required by the test-pod since the CI job might not specify all envs if it is running a particular test.
For e.g in upgrade tests `BUILD_IMAGE` would be false but `OPERATOR_IMAGE` will be unset since it is not needed. And our script does not allow unset variables.

run_e2e: default env variables

---

pkg/controller/restore-operator/sync.go
test/e2e/backup_test.go
test/e2e/e2eutil/spec_util.go

restore operator now can created TLS enabled etcd cluster.
ref: https://github.com/coreos/etcd-operator/issues/1495

*: support tls in restore operator

---

test/pod/README.md

[skip ci]
The `test/pod/test-pod-tmpl.yaml` has env variables related to the upgrade tests that need to be set even if the upgrade tests are not run. The README has been updated to show that.

test/pod: update README for upgrade test variables

---

test/e2e/backup_test.go
test/e2e/e2eutil/spec_util.go

NewEtcdRestore now use a default etcd verison instead of having a parameter to indicate etcd version.

e2e: use default etcd version when creating NewEtcdRestore

---

cmd/restore-operator/main.go
pkg/controller/restore-operator/operator.go

add createCRD flag allowing user to disable etcd restore operator on creating EtcdRestore CRD automatically.

*: add createCRD flag to etcd restore operator

---

cmd/backup-operator/main.go

cmd: add parse() to parse flags in etcd backup operator

---

example/etcd-restore-operator/restore_cr.yaml
pkg/apis/etcd/v1beta2/restore_types.go
pkg/controller/restore-operator/sync.go
test/e2e/backup_test.go
test/e2e/e2eutil/spec_util.go

ref: #1770 
Part 1/2 of #1785 
`EtcdClusterRef` has been simplified by removing the namespace field. The namespace for the reference cluster is always assumed to be the same namespace as the restore-operator.
Support for restoring from an EtcdCluster in a different namespace can be added later.

*: remove namespace from EtcdClusterRef

---

pkg/apis/etcd/v1beta2/backup_types.go

add  EtcdVersion and EtcdRevision to BackupCRStatus to give the backup snapshot information
about the etcd server version that snapshot is based on and what revision of kv store that snapshot contains.

apis: add EtcdVersion and EtcdRevision to BackupCRStatus

---

pkg/apis/etcd/v1beta2/restore_types.go
pkg/controller/restore-operator/sync.go
test/e2e/backup_test.go

ref: #1770
Part 2/2 of #1785
The restore-operator will now delete the reference EtcdCluster and its pods and services completely before creating the restored EtcdCluster.
With this change, the e2e test no longer needs to clean up the pods and services of the reference cluster first.

*: restore-operator deletes EtcdClusterRef completely

---

pkg/apis/etcd/v1beta2/backup_types.go
pkg/backup/backup_manager.go
pkg/controller/backup-operator/s3_backup.go
pkg/controller/backup-operator/sync.go
test/e2e/backup_test.go

ref: https://github.com/coreos/etcd-operator/issues/1763
etcd backup operator now writes EtcdVersion and EtcdRevision into BackupStatus when performing an successful backup.

*: etcd backup operator updates EtcdVersion and EtcdRevision in BackupStatus

---

pkg/apis/etcd/v1beta2/restore_types.go
pkg/controller/restore-operator/http.go
test/e2e/backup_test.go
test/e2e/e2eutil/spec_util.go

ref: https://github.com/coreos/etcd-operator/issues/1763
When RestoreSpec specifies  backupStorageType, restore operator needs to check if backupStorageType matches the RestoreSource.

*: validate BackupStorageType in restore operator

---

test/container/Dockerfile
test/container/docker_push
test/container/run

[skip ci]
The test-container minimizes the dependencies needed to run the e2e tests.
After building the image `TEST_IMAGE` the test-container can be run as:
```sh
docker run -e "KUBECONFIG=/kubeconfig" \
-v "/path/to/local/kubeconfig:/kubeconfig" \
$TEST_IMAGE
```
There is some issue with redirecting the stdout/stderr to a file that can be resolved later.

test/container: run e2e tests from container

---

test/e2e/e2eslow/backup_restore_test.go
test/e2e/tls_test.go

- move tls_test to parallel e2e
- move backup_test.go to e2eslow/backup_restore_test.go

test: reorg test suites

---

pkg/cluster/cluster.go
pkg/util/k8sutil/k8sutil.go
pkg/util/k8sutil/pod_util.go

ref #1320 
Added readiness probe to etcd pod. It's the same as the liveliness probe but the time period for readiness is 10s, shorter than the liveliness 60s.
The operator now checks if all member pods are Ready while updating the member status for ready/unready members.

*: use pod readiness check to update member status

---

hack/ci/run_e2e
hack/test

With `PASSES=""` hack/run_e2e can be used to skip tests and only build images.

hack/run_e2e: support skipping tests

---

CHANGELOG.md
README.md
doc/user/spec_examples.md
doc/user/walkthrough/backup-operator.md
example/example-etcd-cluster.yaml
pkg/apis/etcd/v1beta2/cluster.go
test/e2e/basic_test.go
test/e2e/e2esh/self_hosted_test.go
test/e2e/e2eslow/backup_restore_test.go

bump etcd version to 3.2.13 in many places.
exposed DefaultVersion allowing backup_restore_test.go to use it to compare 
backup status with the default etcd version.
fixes #1813

*: bump etcd verison to 3.2.13

---

test/container/run

[skip ci]
The test logs are saved at /out and are also shown on the console.

test/container: redirect test logs to /out

---

CHANGELOG.md
cmd/restore-operator/main.go
cmd/restore-operator/service.go
doc/user/walkthrough/restore-operator.md
example/etcd-restore-operator/deployment.yaml
test/e2e/framework/framework.go

address https://github.com/coreos/etcd-operator/issues/1836

restore-operator: create service itself

---

pkg/util/k8sutil/k8sutil.go
pkg/util/k8sutil/pod_util.go

ref: https://github.com/coreos/etcd-operator/issues/1182#issuecomment-356372426
We need to apply user specified PodPolicy.Resources to all containers in etcd pod, instead of only on etcd container.

*: apply podPolicy.Resources to all containers in etcd pod

---

pkg/util/k8sutil/k8sutil.go

Also fix the ordering to apply pod policy on recovery containers too
ref: https://github.com/coreos/etcd-operator/issues/1825#issuecomment-357046772

k8sutil: add recovery container instead of overriding

---

pkg/apis/etcd/v1beta2/backup_types.go
pkg/apis/etcd/v1beta2/restore_types.go
pkg/controller/backup-operator/s3_backup.go
pkg/controller/restore-operator/http.go
pkg/util/awsutil/s3factory/client.go
pkg/util/awsutil/s3factory/client_test.go
test/e2e/e2eslow/backup_restore_test.go

this enables backup on other implementations of S3, such as ceph and minio.

backup: custom S3 endpoint support

---

pkg/util/k8sutil/k8sutil.go

ref: #806 
With the given pod security context, the etcd containers will run as the non-root user 9000, and any volumes will have permissions for the group 9000 allowing the etcd process to read/write to them.

k8sutil: run etcd pods as non-root user

---

test/e2e/e2eslow/backup_restore_test.go

s3cli is not being used anywhere; remove unused code.

e2e: remove unused code in testEtcdBackupOperatorForS3Backup

---

pkg/cluster/reconcile.go
pkg/util/k8sutil/k8sutil.go

Sort out serror case and put error message into termination log.
ref: https://github.com/coreos/etcd-operator/issues/1860
ref: https://github.com/coreos/etcd-operator/issues/1825

*: improve restore init container error message

---

test/e2e/e2eslow/backup_restore_test.go

discussed from https://github.com/coreos-inc/vault-operator/pull/255

e2e: change retry timeout to 10s in testEtcdRestoreOperatorForS3Source

---

pkg/cluster/cluster.go
pkg/cluster/member.go
pkg/cluster/reconcile.go
pkg/cluster/self_hosted.go
pkg/controller/restore-operator/sync.go
pkg/util/etcdutil/member.go
pkg/util/k8sutil/k8sutil.go

address https://github.com/coreos/etcd-operator/issues/1872

*: make each new member name unique

---

CHANGELOG.md

CHANGELOG: update

---

pkg/util/k8sutil/k8sutil.go

Rather than specify an ImagePullPolicy, specify a tag for
initContainer image.  This addresses disconnected installs without
changing podspec default settings.
Fixes #1894

Add tag to initContainer to enable offline deploys

---

cmd/operator/main.go

Usually signal.Notify() is used for the main thread to wait for children
threads to complete for graceful shutdown. We aren't doing any of this.
This part of code was added as a way to print SIGTERM. Not needed anyway.
Original PR: https://github.com/coreos/etcd-operator/pull/750
fix https://github.com/coreos/etcd-operator/issues/1892

cmd: do not receive signal

---

pkg/backup/backup_manager.go
pkg/controller/backup-operator/sync.go
pkg/controller/backup-operator/sync_test.go

fix https://github.com/coreos/etcd-operator/issues/1893
Tested with empty endpoints:
```
status:
Reason: spec.etcdEndpoints could not be empty
succeeded: false
```
Should be better handled by initializer/admission plugin: https://github.com/coreos/etcd-operator/issues/1392

*: reject empty endpoints in EtcdBackup CR

---

README.md

[skip ci]
This point was for the pivoting cluster to self-hosted case. Doesn't exist anymore

README: readme outdated point

---

doc/user/spec_examples.md
pkg/apis/etcd/v1beta2/cluster.go
pkg/apis/etcd/v1beta2/zz_generated.deepcopy.go
pkg/util/k8sutil/k8sutil.go
pkg/util/k8sutil/pod_util.go

Annotations are a way to attach metadata to Kubernetes objects. This PR extends the operator configuration with an option to attach annotations to pods that the operator creates for the cluster. A
use case for this is prometheus using annotations to identify pods from which metrics can be scraped, including pod-specific scraping configuration. The changes in this PR would enable users to configure
etcd pods created by the operator to be annotated for scraping by prometheus.

k8sutil: make pod annotations configurable

---

pkg/apis/etcd/v1beta2/backup_types.go
pkg/backup/backup_manager.go
pkg/controller/backup-operator/abs_backup.go
pkg/controller/backup-operator/s3_backup.go
pkg/controller/backup-operator/sync.go
pkg/util/constants/constants.go

ref: https://github.com/coreos/etcd-operator/issues/1906

*: implement configurable backup timeout

---

pkg/backup/backup_manager.go
pkg/backup/writer/abs_writer.go
pkg/backup/writer/s3_writer.go
pkg/backup/writer/writer.go

backup/writer interface now reasons about input context. The context controls the writer.Write operation.
ref: https://github.com/coreos/etcd-operator/issues/1906

*: support Writer with context

---

pkg/apis/etcd/v1beta2/cluster.go
pkg/controller/backup-operator/sync.go
pkg/util/k8sutil/k8sutil.go

fix https://github.com/coreos/etcd-operator/issues/1909

 k8sutil: set 30s default request timeout for kube client

---

pkg/util/k8sutil/k8sutil.go

The image currently used is busybox:1.28.0 which uses uclibc.  This is
causing nslookup to fail name resolution when it shouldn't in some
environments.  The version of busybox that uses glibc does not suffer the
same problem.
Related:
https://github.com/docker-library/busybox/issues/9
https://github.com/docker-library/busybox/issues/27

pkg/util: Change check-dns init container image

---

CHANGELOG.md
example/deployment.yaml
example/etcd-backup-operator/deployment.yaml
example/etcd-restore-operator/deployment.yaml
version/version.go

same as 0.8.4. bump to 0.9.0 due to adding a new abs backup api.
[skip ci]

release: bump version to 0.9.0

---

pkg/apis/etcd/v1beta2/cluster.go
pkg/util/k8sutil/k8sutil.go
pkg/util/k8sutil/k8sutils_test.go

cluster: add option to specify busybox repository 
add 2 options in EtcdCluster.spec:
busyboxRepository. Defaults to "busybox"
busyboxVersion. Defaults to "1.28.0-glibc"
for #1927

cluster: add option to specify busybox repository

---

Gopkg.lock
Gopkg.toml
hack/build/build
hack/build/e2e/builder/Dockerfile
hack/ci/get_dep
hack/test

Update dep to 0.4.1. Dep is developing fast and we better keep up with it to catch bug fix and also community docs.
0.4 dep rules will by default apply major range operator '^' on semantic versions. Thus we need to pin the version explicitly.
For non-semantic versions like tags this is fine.

Update dep to 0.4 and change respective rules

---

pkg/util/k8sutil/k8sutil.go

The watch stream in informer will break after 30s:
```
E0306 20:38:49.476999       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
```

k8sutil: remove global defaultKubeAPIRequestTimeout

---

CHANGELOG.md
doc/dev/developer_guide.md
hack/build/backup-operator/build
hack/build/build
hack/build/e2e/builder/Dockerfile
hack/build/logcollector/Dockerfile
hack/build/operator/build
hack/build/restore-operator/build
hack/ci/get_dep
hack/ci/run_e2e
hack/ci/run_unit
hack/fmt_pass
hack/test
hack/unit_test
test/container/Dockerfile
test/pod/Dockerfile

Go version is defined in
- build
- test script
This PR updates them. Also some cleanup.
fix https://github.com/coreos/etcd-operator/issues/1752

*: update go version to 1.10

---

doc/best_practices.md
doc/design/cluster_status.md

Fixes misspellings of Kubernetes and removes some extraneous whitespace

doc: fix misspelling of Kubernetes

---

pkg/apis/etcd/v1beta2/cluster.go
pkg/apis/etcd/v1beta2/zz_generated.deepcopy.go
pkg/util/k8sutil/k8sutil.go

*: make SecurityContext configurable via PodPolicy

---

pkg/apis/etcd/v1beta2/cluster.go
pkg/util/k8sutil/k8sutil.go

Adding a timeout for waiting on the DNS entry to exists. This prevents the init container to be in an inifinite loop in case of a failure of registering the DNS on startup
We have seen this happening on GKE with preemptive nodes where the pod got created before the network was able to assign it an IP causing the init container to be stuck forever in this loop.

Add a time-out for waiting on DNS

---

test/e2e/framework/framework.go
test/pod/simple/Dockerfile
test/pod/simple/run-e2e
test/pod/simple/simple-pod-templ.yaml

Added a simplified version of the current [test/pod](https://github.com/coreos/etcd-operator/blob/master/test/pod/test-pod-templ.yaml) to reduce the number of configurations.
Modified the e2e test framework to skip the operator setup if no test image is provided.
This way the test-pod can be used to run e2e tests in a namespace with an already deployed etcd-operator.
The default cmd is set to `run-e2e` which only runs the e2e tests for now.
The [e2e-slow](https://github.com/coreos/etcd-operator/tree/master/test/e2e/e2eslow) tests are not run for now because they require aws creds or modify the deployed operator which requires the operator image env.
The Dockerfile for the simplified test pod is 2 staged. The first stage builds the test binary and the second stage adds the test binary to …

test: run e2e test pod without framework setup

---

README.md

Due to a Jenkins upgrade (I think?) the URL for the unit test badge
changed. Fix this.

README: update URL to unit test badge

---

pkg/apis/etcd/v1beta2/backup_types.go
pkg/util/azureutil/absfactory/client.go

PR #1842 adds support for ABS (Azure Blob Service) backup. But it always using AzurePublicCloud, so that other sovereign clouds (e.g. mooncake) won't work.
This PR adds an extra option `cloud` to ABS credential and use `storage.NewBasicClientOnSovereignCloud()`  to fix the issue. If `cloud` is not set, then AzurePublicCloud is used (same as before).
Example ABS credential now is
```yaml
apiVersion: v1
kind: Secret
metadata:
name: abs-credentials
type: Opaque
stringData:
storage-account: <storage-account-name>
storage-key: <storage-key>
cloud: AzurePublicCloud
```

Add cloud environment support for ABS backup

---

pkg/util/k8sutil/pod_util.go

Change the probe to check `endpoint health` instead of `get foo` so that enabling authorization does not take down the cluster.

Avoid probe failure from auth enable

---

doc/user/spec_examples.md

[skip ci]
- How to use dynamically provisioned PVCs with explicitly defined StorageClass
- Anti affinity example with Preferred rather than Required affinity to deploy members in different nodes if possible.

Add cluster spec examples

---

CHANGELOG.md
pkg/cluster/cluster.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/controller/informer.go

This patch uses `<namespace>/<cluster-name>` as key to store the cluster in Controller struct to avoid over-writing same named CR's in different namespaces.
Fixes #1954
Please read https://github.com/coreos/etcd-operator/blob/master/CONTRIBUTING.md#contribution-flow

pkg/controller: Fix CR with same name in different namespaces

---

test/e2e/e2eslow/backup_restore_test.go

This PR is to cleanup CI failures
```
ok  	github.com/coreos/etcd-operator/test/e2e	198.722s
test/e2e/e2eslow/backup_restore_test.go:192:45: not enough arguments in call to s3factory.NewClientFromSecret
have (kubernetes.Interface, string, string, string)
want (kubernetes.Interface, string, string, string, bool)
```

test/e2e/e2eslow: fix restore tests

---

CHANGELOG.md
Gopkg.lock
Gopkg.toml
cmd/backup-operator/main.go
cmd/operator/main.go
cmd/restore-operator/main.go
hack/build/e2e/builder/Dockerfile
hack/build/logcollector/Dockerfile
hack/test
pkg/controller/backup-operator/sync.go
pkg/controller/backup-operator/util.go
pkg/generated/clientset/versioned/fake/register.go
pkg/generated/clientset/versioned/scheme/register.go
test/container/Dockerfile
test/logcollector/main.go
test/pod/Dockerfile
test/pod/simple/Dockerfile

This PR bumps k8s to 1.12.6, golang to 1.11.5 and regenerated codegen.
Signed-off-by: Sam Batschelet <sbatsche@redhat.com>

dep: bump k8s to 1.12.6 and regenerate codegen

---

CHANGELOG.md
pkg/util/k8sutil/k8sutil.go

Previously unready etcd nodes were already receiving client connections
although they are still in the initiation phase and not able to accept
any traffic. This caused connection failure or high latency.
Fixes #2030

pkg/util: Don't expose unready nodes via client service

---

CHANGELOG.md
pkg/backup/writer/abs_writer.go

Azure bloc storage implementation didn't use the right prefix resulting on no backup cleanup being performed.

Azure blob storage: use correct list prefix

---

CHANGELOG.md
pkg/apis/etcd/v1beta2/cluster.go
pkg/cluster/cluster.go
pkg/cluster/member.go
pkg/controller/restore-operator/sync.go
pkg/util/etcdutil/member.go

This allows setting the cluster domain as a flag on the operator. The
cluster domain is used as a suffix in the Client URLs for the etcd
members.
The ability to set a custom cluster domain is desirable when running in
clusters with a custom DNS configuration.
In our case we need this because we have decided to default the DNS config to use `ndots:2` instead of the default `ndots:5` setting which can result in up to 10 additional DNS queries for every single name lookup, which causes an unnecessary overhead for the DNS infrastructure and for applications.
Ref: https://github.com/kubernetes/dns/issues/159#issuecomment-336449931
An alternative way to fix this would be to allow specifying the DNS config of the pod spec: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#p …

Allow specifying Cluster Domain for clientURLs
